"""mem_stream_gen.py — codegen driver for the standalone ``MemRStream`` / ``MemWStream`` kernels.

Their kernel body is **FIXED** (= the validated sandbox ``a2s`` / ``s2a``), shipped as the
width-templated ``template<int MEM_DW>`` task bodies ``waveflow/build/mem_{r,w}_stream_task.h``
(copied by :class:`~waveflow.build.streamutils.MemStreamStep`).  So codegen is a **template**, not a
``run_iter`` extraction (the framework ``HlsCodegenStep`` emits an ``ap_ctrl_hs`` top with no
``hls::task``; we need a free-running ``ap_ctrl_none`` single-``hls::task`` kernel).

This module is the **example driver**: which components to emit, and where.  The top model and
renderers it uses are framework — :mod:`waveflow.build.composite_gen` — where a standalone kernel is
the 1-task degenerate case of an N-task composite top.  The command struct stays generated by
``DataSchemaStep``.

Run (project venv, from repo root)::

    PYTHONPATH=. pysilicon-venv/Scripts/python.exe examples/interleaver/mem_stream_gen.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO))

from waveflow.build.build import BuildConfig, BuildDag  # noqa: E402
from waveflow.build.composite_gen import (  # noqa: E402
    DEFAULT_MEM_DW,
    GEN_DIR,
    INCLUDE_DIR,
    TaskInst,
    TopSpec,
    _axis_port,
    _maxi_port,
    render_ports_h,
    render_tcl,
    render_top,
)
from waveflow.build.streamutils import MemMgrStep, MemStreamStep, StreamUtilsStep  # noqa: E402
from waveflow.hw.dataschema import DataSchemaStep  # noqa: E402
from waveflow.hw.mem_stream import (  # noqa: E402
    MRCmd,
    MWCmd,
    MemRStream,
    MemWStream,
    SCHEMA_CLASSES,
    WORD_BW_SUPPORTED,
)


def top_spec_for(comp_class, width: int = DEFAULT_MEM_DW) -> TopSpec:
    """Build the :class:`TopSpec` for a standalone mem-stream kernel (the 1-task degenerate case)."""
    if comp_class is MemRStream:
        return TopSpec(
            top_name="mem_r_stream",
            ports=(_axis_port("s_cmd", width, kind="axis_in"),
                   _maxi_port("m_mem", width, const=True),
                   _axis_port("m_out", width, kind="axis_out")),
            tasks=(TaskInst("mem_r_stream_task", (width,), ("s_cmd", "m_mem", "m_out"),
                            "mem_r_stream_task.h"),),
            cmd_headers=(MRCmd.resolved_include_filename(),),
        )
    if comp_class is MemWStream:
        return TopSpec(
            top_name="mem_w_stream",
            ports=(_axis_port("s_cmd", width, kind="axis_in"),
                   _axis_port("s_in", width, kind="axis_in"),
                   _maxi_port("m_mem", width, const=False)),
            tasks=(TaskInst("mem_w_stream_task", (width,), ("s_cmd", "s_in", "m_mem"),
                            "mem_w_stream_task.h"),),
            cmd_headers=(MWCmd.resolved_include_filename(),),
        )
    raise ValueError(f"no mem-stream top template for {comp_class!r}")



# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def gen_headers(config: BuildConfig) -> None:
    """Generate the command-struct headers + memmgr.hpp + streamutils_hls.h + the fixed
    mem-stream task-body headers into ``include/``."""
    inner = BuildDag()
    inner.add(StreamUtilsStep(output_dir=INCLUDE_DIR))
    inner.add(MemMgrStep(output_dir=INCLUDE_DIR))
    inner.add(MemStreamStep(output_dir=INCLUDE_DIR))   # mem_{r,w}_stream_task.h (the fixed bodies)
    for cls in SCHEMA_CLASSES:
        inner.add(DataSchemaStep(cls, word_bw_supported=WORD_BW_SUPPORTED,
                                 include_dir=INCLUDE_DIR))
    results = inner.run(config, force=True)
    failed = [n for n, r in results.items() if not r.success]
    if failed:
        raise RuntimeError(f"gen-include failed: {failed}")


def generate(out_dir: Path = HERE, width: int = DEFAULT_MEM_DW) -> dict[str, Path]:
    """Generate headers + the two kernel top .cpp + their csynth .tcl into *out_dir*."""
    config = BuildConfig(root_dir=out_dir, params={})
    gen_headers(config)
    gen = out_dir / GEN_DIR
    gen.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    for comp_class in (MemRStream, MemWStream):
        spec = top_spec_for(comp_class, width=width)
        cpp = gen / f"{spec.top_name}.cpp"
        cpp.write_text(render_top(spec), encoding="utf-8")
        tcl = out_dir / f"{spec.top_name}.tcl"
        tcl.write_text(render_tcl(spec.top_name), encoding="utf-8")
        ports_h = out_dir / "xsi" / f"{spec.top_name}_ports.h"
        ports_h.parent.mkdir(parents=True, exist_ok=True)
        ports_h.write_text(render_ports_h(spec), encoding="utf-8")
        written[spec.top_name] = cpp
        print(f"generated {cpp.relative_to(out_dir)} + {tcl.name} + xsi/{ports_h.name}")
    return written


if __name__ == "__main__":
    generate()
