"""mem_stream_gen.py — codegen orchestration for the ``MemRStream`` / ``MemWStream`` kernels.

Their kernel body is **FIXED** (= the validated sandbox ``a2s`` / ``s2a``), shipped as the
width-templated ``template<int MEM_DW>`` task bodies ``waveflow/build/mem_{r,w}_stream_task.h``
(copied by :class:`~waveflow.build.streamutils.MemStreamStep`).  So codegen is a **template**, not a
``run_proc`` extraction (the framework ``HlsCodegenStep`` emits an ``ap_ctrl_hs`` top with no
``hls::task``; we need a free-running ``ap_ctrl_none`` single-``hls::task`` kernel).

The generated **top** bakes a *concrete* width (``ap_uint<64>``, ``mem_r_stream_task<64>``) — no
``#define MEM_DW`` — instantiates the template body, and emits the interface pragmas + ``ap_ctrl_none``
+ ``hls_thread_local hls::task``.  The top generator (:func:`render_top`) is structured so a
standalone kernel is the **1-component degenerate case** of an N-component composite top (P2 extends
it with internal ``hls_thread_local`` streams wiring several tasks).  The command struct stays
generated by ``DataSchemaStep``.

Run (project venv, from repo root)::

    PYTHONPATH=. pysilicon-venv/Scripts/python.exe examples/interleaver/mem_stream_gen.py
"""
from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO))

from waveflow.build.build import BuildConfig, BuildDag  # noqa: E402
from waveflow.build.streamutils import MemMgrStep, MemStreamStep, StreamUtilsStep  # noqa: E402
from waveflow.hw.dataschema import DataSchemaStep  # noqa: E402
from waveflow.hw.mem_stream import (  # noqa: E402
    MRCmd,
    MWCmd,
    MemRStream,
    MemWStream,
    SCHEMA_CLASSES,
    WORD_BW_SUPPORTED,
)

INCLUDE_DIR = "include"
GEN_DIR = "gen"
DEFAULT_MEM_DW = 64


# ---------------------------------------------------------------------------
# Composite-ready top model (a standalone kernel = the 1-task degenerate case)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ExtPort:
    """One external interface port of the generated top: its C++ param decl + interface pragmas."""
    decl: str
    pragmas: tuple[str, ...]


@dataclass(frozen=True)
class TaskInst:
    """One ``hls::task`` instantiation inside the top: the width-templated body + its call args."""
    task_fn: str            # e.g. "mem_r_stream_task"
    width: int              # baked-concrete MEM_DW, e.g. 64
    args: tuple[str, ...]   # arg names (external ports and/or internal streams), in signature order
    header: str             # the task-body header to include


@dataclass(frozen=True)
class TopSpec:
    """A generated free-running (``ap_ctrl_none``) ``hls::task`` top.  For a standalone kernel there
    is one task and no internal streams; a composite (P2) adds tasks + ``hls_thread_local`` streams
    wiring their internal edges, keeping the external ports the composite's boundary."""
    top_name: str
    ports: tuple[ExtPort, ...]              # external interface ports (signature order)
    tasks: tuple[TaskInst, ...]
    cmd_headers: tuple[str, ...]            # command struct headers to include
    internal_streams: tuple[str, ...] = ()  # hls_thread_local decls (empty for a standalone kernel)


def _axis_port(name: str, width: int) -> ExtPort:
    return ExtPort(f"hls::stream<ap_uint<{width}> >& {name}",
                   (f"#pragma HLS INTERFACE axis port={name}",))


def _maxi_port(name: str, width: int, *, const: bool) -> ExtPort:
    """An ``m_axi`` master port.  The read owner is ``const`` (the ``@port_read`` capability -> a
    stray write is a compile error) and gets ``#pragma HLS stable``; the write owner is plain."""
    qual = "const " if const else ""
    pragmas = [f"#pragma HLS INTERFACE m_axi port={name} offset=slave bundle=gmem0 depth=8192"]
    if const:
        pragmas.append(f"#pragma HLS stable variable={name}")
    return ExtPort(f"{qual}ap_uint<{width}>* {name}", tuple(pragmas))


def top_spec_for(comp_class, width: int = DEFAULT_MEM_DW) -> TopSpec:
    """Build the :class:`TopSpec` for a standalone mem-stream kernel (the 1-task degenerate case)."""
    if comp_class is MemRStream:
        return TopSpec(
            top_name="mem_r_stream",
            ports=(_axis_port("s_cmd", width),
                   _maxi_port("m_mem", width, const=True),
                   _axis_port("m_out", width)),
            tasks=(TaskInst("mem_r_stream_task", width, ("s_cmd", "m_mem", "m_out"),
                            "mem_r_stream_task.h"),),
            cmd_headers=(MRCmd.resolved_include_filename(),),
        )
    if comp_class is MemWStream:
        return TopSpec(
            top_name="mem_w_stream",
            ports=(_axis_port("s_cmd", width),
                   _axis_port("s_in", width),
                   _maxi_port("m_mem", width, const=False)),
            tasks=(TaskInst("mem_w_stream_task", width, ("s_cmd", "s_in", "m_mem"),
                            "mem_w_stream_task.h"),),
            cmd_headers=(MWCmd.resolved_include_filename(),),
        )
    raise ValueError(f"no mem-stream top template for {comp_class!r}")


def render_top(spec: TopSpec) -> str:
    """Emit the generated free-running ``ap_ctrl_none`` ``hls::task`` top .cpp for *spec*.

    Composite-ready: iterates *spec.ports* (external boundary), *spec.internal_streams*
    (``hls_thread_local`` FIFOs — empty for a standalone kernel), and *spec.tasks*
    (``hls::task`` instances at a baked concrete width).  No ``#define MEM_DW`` and no ``while`` —
    the width is a template argument and the ``hls::task`` runtime re-fires each single-firing body."""
    task_headers = tuple(dict.fromkeys(t.header for t in spec.tasks))  # unique, order-preserving
    includes = ["hls_task.h", "hls_stream.h"]
    lines = [
        f"// {spec.top_name}.cpp — GENERATED (examples/interleaver/mem_stream_gen.py).",
        "// DO NOT EDIT: free-running (ap_ctrl_none) hls::task top; the fixed task bodies are the",
        "// validated sandbox a2s/s2a (waveflow/build/mem_*_stream_task.h). Verify via XSI —",
        "// ap_ctrl_none Vitis cosim is unreliable.",
    ]
    lines += [f'#include "{h}"' for h in includes]
    lines.append("#include <ap_int.h>")
    lines.append('#include "memmgr.hpp"')
    lines += [f'#include "{h}"' for h in spec.cmd_headers]
    lines += [f'#include "{h}"' for h in task_headers]
    lines.append("")

    port_decls = ",\n".join(f"    {p.decl}" for p in spec.ports)
    lines.append(f"void {spec.top_name}(")
    lines.append(port_decls)
    lines.append(") {")
    for p in spec.ports:
        lines += list(p.pragmas)
    lines.append("#pragma HLS INTERFACE ap_ctrl_none port=return")
    for s in spec.internal_streams:               # empty for a standalone kernel (P2 composite)
        lines.append(f"    {s}")
    for i, t in enumerate(spec.tasks):
        call_args = ", ".join(t.args)
        lines.append(
            f"    hls_thread_local hls::task t{i}({t.task_fn}<{t.width}>, {call_args});")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_tcl(top_name: str) -> str:
    """Emit a csynth ``.tcl`` for ``vitis-run --mode hls --tcl`` (concrete width baked in, so the
    cflags carry only the include path — no ``-DMEM_DW``)."""
    return f"""\
set part {{xc7z020clg484-1}}
set cf "-I{INCLUDE_DIR}"
puts "WAVEFLOW_INFO: {top_name}"
open_project -reset {top_name}_proj
set_top {top_name}
add_files {GEN_DIR}/{top_name}.cpp -cflags $cf
open_solution -reset "solution1"
set_part $part
create_clock -period 10
if {{[catch {{csynth_design}} res]}} {{ puts "WAVEFLOW_ERROR: csynth"; puts $res; exit 1 }}
puts "WAVEFLOW_CSYNTH_OK"
exit 0
"""


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def gen_headers(config: BuildConfig) -> None:
    """Generate the command-struct headers + memmgr.hpp + streamutils_hls.h + the fixed
    mem-stream task-body headers into ``include/``."""
    inner = BuildDag()
    inner.add(StreamUtilsStep(output_dir=INCLUDE_DIR))
    inner.add(MemMgrStep(output_dir=INCLUDE_DIR))
    inner.add(MemStreamStep(output_dir=INCLUDE_DIR))   # mem_{r,w}_stream_task.h (the fixed bodies)
    for cls in SCHEMA_CLASSES:
        inner.add(DataSchemaStep(cls, word_bw_supported=WORD_BW_SUPPORTED,
                                 include_dir=INCLUDE_DIR))
    results = inner.run(config, force=True)
    failed = [n for n, r in results.items() if not r.success]
    if failed:
        raise RuntimeError(f"gen-include failed: {failed}")


def generate(out_dir: Path = HERE, width: int = DEFAULT_MEM_DW) -> dict[str, Path]:
    """Generate headers + the two kernel top .cpp + their csynth .tcl into *out_dir*."""
    config = BuildConfig(root_dir=out_dir, params={})
    gen_headers(config)
    gen = out_dir / GEN_DIR
    gen.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    for comp_class in (MemRStream, MemWStream):
        spec = top_spec_for(comp_class, width=width)
        cpp = gen / f"{spec.top_name}.cpp"
        cpp.write_text(render_top(spec), encoding="utf-8")
        tcl = out_dir / f"{spec.top_name}.tcl"
        tcl.write_text(render_tcl(spec.top_name), encoding="utf-8")
        written[spec.top_name] = cpp
        print(f"generated {cpp.relative_to(out_dir)} + {tcl.name}")
    return written


if __name__ == "__main__":
    generate()
