#ifndef WAVEFLOW_GEN_BRAM_TOY_TB_HARNESS_H
#define WAVEFLOW_GEN_BRAM_TOY_TB_HARNESS_H
// bram_toy_tb_harness.h -- GENERATED by waveflow (build/composite_gen.py::render_tb_harness)
// from the bram_toy testbench graph.  DO NOT EDIT: regenerate instead.
//
// The derivable half of an XSI testbench: which models drive which RTL ports, the three
// per-cycle phases, and the run loop.  What it deliberately does NOT contain is the TEST --
// what goes in memory and what is checked afterwards.  Those are the golden, and the graph
// cannot know them.
#include <cstdint>
#include <string>
#include <vector>
#include "xsi_bfm.h"
#include "bram_toy_ports.h"

namespace bram_toy_tb {

using namespace wfbfm;

struct Harness {
    // Declaration order IS construction order: the sim must exist before any model can
    // resolve a port against it, and a shared arena before the slaves that serve from it.
    XsiSim sim;
    AxisMaster rx_str;
    AxisMaster addr_str;
    AxisSlave out_str;
    // Every participant by base pointer, in construction order (shared arenas
    // first): the one list the five lifecycle phases iterate, mirroring how
    // Simulation.run_sim() drives its SimObjs.
    std::vector<wfbfm::XsiSimObj*> participants_;

    explicit Harness(const std::string& wdb)
      : sim(bram_toy_ports::DESIGN_DLL, wdb),
        rx_str(sim.dut(), bram_toy_ports::rx_str, {}),
        addr_str(sim.dut(), bram_toy_ports::addr_str, {}),
        out_str(sim.dut(), bram_toy_ports::out_str)
    {
        // Every TB-driven input the models above do not themselves drive.  Absent
        // names are skipped; an undriven input is X, and X on a handshake hangs.
        sim.pin_low(bram_toy_ports::ZERO_PORTS, bram_toy_ports::ZERO_PORTS_N);
        // Register participants for the lifecycle phases (shared arenas first, so a
        // memory's pre_sim runs before the models that serve from it).
        participants_.push_back(&rx_str);
        participants_.push_back(&addr_str);
        participants_.push_back(&out_str);
        // Init-time config (DynParams): each is a knob the pysim participant
        // carries, emitted here as a member assignment (e.g. a model's bundle).
        rx_str.in_bundle = "vectors/rx";
        addr_str.in_bundle = "vectors/addr";
        out_str.out_bundle = "vectors/out";
    }
    void pre_sim() { for (auto* p : participants_) p->pre_sim(); }
    void sample() { for (auto* p : participants_) p->sample(); }
    void update() { for (auto* p : participants_) p->update(); }
    void drive() { for (auto* p : participants_) p->drive(); }
    void post_sim() { for (auto* p : participants_) p->post_sim(); }

    /// Run exactly *n_cycles*.  No early termination: see the note in the file header --
    /// nothing blocks, so the DUT's pipelining survives by construction.  Undersize n and
    /// the caller's own completion check fails loudly rather than passing quietly.
    void run(long n_cycles) {
        pre_sim();                       // participants seed memory / load vectors
        sim.reset([this]{ drive(); });
        for (long c = 0; c < n_cycles; ++c) {
            sim.clock_low();
            sample();
            sim.clock_high();
            update();
            drive();
        }
        post_sim();                      // participants dump results / collect metrics
    }

    void close() { sim.close(); }
};

}  // namespace bram_toy_tb

#endif  // WAVEFLOW_GEN_BRAM_TOY_TB_HARNESS_H
