#ifndef WAVEFLOW_GEN_BRAM_TOY_PORTS_H
#define WAVEFLOW_GEN_BRAM_TOY_PORTS_H
// bram_toy_ports.h -- GENERATED by waveflow (build/composite_gen.py::render_ports_h) from the SAME
// TopSpec that emits bram_toy's interface pragmas.  DO NOT EDIT: regenerate instead.
// One spec, two consumers -- so a testbench cannot drift from the kernel it drives.

namespace bram_toy_ports {

static const char* const TOP        = "bram_toy_top";

// xelab -dll emits the platform's native shared library, so the name differs by OS.  The
// conditional lives in the generated header rather than in the generator so ONE emitted
// header serves a Windows and a Linux build of the same testbench.
#ifdef _WIN32
static const char* const DESIGN_DLL = "xsim.dir/bram_toy_top/xsimk.dll";
#else
static const char* const DESIGN_DLL = "xsim.dir/bram_toy_top/xsimk.so";
#endif

static const char* const rx_str   = "rx_str";   // axis_in
static const char* const addr_str = "addr_str";   // axis_in
static const char* const out_str  = "out_str";   // axis_out

// Every TB-driven input the interface models above do not themselves drive.  Absent names
// are skipped at bind time (XsiSim::pin_low), so this may name channels a given kernel
// does not expose.
static const char* const ZERO_PORTS[] = {
};
static const int ZERO_PORTS_N = (int)(sizeof(ZERO_PORTS)/sizeof(ZERO_PORTS[0]));

}  // namespace bram_toy_ports

#endif  // WAVEFLOW_GEN_BRAM_TOY_PORTS_H
