// bram_toy_top.v — GENERATED by waveflow (build/wrapper_gen.py::render_wrapper).
// DO NOT EDIT: regenerate instead.
//
// The design scope: the generated kernel `bram_toy` plus the hand-written memories it
// reaches through `mode=bram` ports.  The kernel cannot contain them (Vitis turns an array
// shared between two tasks into a synchronizing PIPO channel, and refuses one port used both
// ways), so they live beside it and this module is what joins them.
//
// From outside this looks like a kernel with only its AXI-Stream ports — the memories are
// internal and invisible to any testbench.  It is also what a resource estimate should
// count: csynth of the kernel alone never sees them.
`timescale 1ns/1ps
module bram_toy_top (
    input  ap_clk,
    input  ap_rst_n,
    input  [15:0] rx_str_TDATA,
    input  rx_str_TVALID,
    output rx_str_TREADY,
    input  [15:0] addr_str_TDATA,
    input  addr_str_TVALID,
    output addr_str_TREADY,
    output [15:0] out_str_TDATA,
    output out_str_TVALID,
    input  out_str_TREADY
);

    wire [31:0] buf_w_addr_a;
    wire [15:0] buf_w_din_a;
    wire [15:0] buf_w_dout_a;
    wire buf_w_en_a;
    wire [1:0] buf_w_we_a;
    wire [15:0] buf_w_dout_b;
    wire [31:0] buf_r_addr_a;
    wire [15:0] buf_r_din_a;
    wire [15:0] buf_r_dout_a;
    wire buf_r_en_a;
    wire [1:0] buf_r_we_a;
    wire [15:0] buf_r_dout_b;

    bram_toy kernel (
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        .rx_str_TDATA(rx_str_TDATA),
        .rx_str_TVALID(rx_str_TVALID),
        .rx_str_TREADY(rx_str_TREADY),
        .addr_str_TDATA(addr_str_TDATA),
        .addr_str_TVALID(addr_str_TVALID),
        .addr_str_TREADY(addr_str_TREADY),
        .out_str_TDATA(out_str_TDATA),
        .out_str_TVALID(out_str_TVALID),
        .out_str_TREADY(out_str_TREADY),
        .buf_w_Addr_A(buf_w_addr_a),
        .buf_w_Din_A(buf_w_din_a),
        .buf_w_Dout_A(buf_w_dout_a),
        .buf_w_EN_A(buf_w_en_a),
        .buf_w_WEN_A(buf_w_we_a),
        .buf_w_Addr_B(),
        .buf_w_EN_B(),
        .buf_w_Din_B(),
        .buf_w_WEN_B(),
        .buf_w_Dout_B(buf_w_dout_b),
        .buf_w_Clk_A(),
        .buf_w_Clk_B(),
        .buf_w_Rst_A(),
        .buf_w_Rst_B(),
        .buf_r_Addr_A(buf_r_addr_a),
        .buf_r_Din_A(buf_r_din_a),
        .buf_r_Dout_A(buf_r_dout_a),
        .buf_r_EN_A(buf_r_en_a),
        .buf_r_WEN_A(buf_r_we_a),
        .buf_r_Addr_B(),
        .buf_r_EN_B(),
        .buf_r_Din_B(),
        .buf_r_WEN_B(),
        .buf_r_Dout_B(buf_r_dout_b),
        .buf_r_Clk_A(),
        .buf_r_Clk_B(),
        .buf_r_Rst_A(),
        .buf_r_Rst_B()
    );

    bram_t2p #(.DW(16), .AW(10)) mem (
        .clk(ap_clk),
        .a_addr(buf_w_addr_a >> 1),
        .a_din(buf_w_din_a),
        .a_dout(buf_w_dout_a),
        .a_en(buf_w_en_a),
        .a_we(|buf_w_we_a),
        .b_addr(buf_r_addr_a >> 1),
        .b_din(buf_r_din_a),
        .b_dout(buf_r_dout_a),
        .b_en(buf_r_en_a),
        .b_we(|buf_r_we_a)
    );

    // The B half of each bram interface: Vitis emits a full A/B pair whether or
    // not the kernel uses both, so its Dout INPUT must be driven.
    assign buf_w_dout_b = 16'd0;
    assign buf_r_dout_b = 16'd0;
endmodule
