// GENERATED by waveflow.build.trace_steps.AddVcdTopStep -- do not edit.
//
// Elaborated as a SECOND top alongside `rf_repeat_play` (see run.bat's `trace` argument), so the XSI
// top -- and therefore every BFM port number -- is untouched.
//
// Level 1 = this scope's OWN signals, no descent into children.  That is already enough: Vitis
// lifts inter-task dataflow channel wires up into the top scope beside the task instances, so the
// internal FIFOs are reachable with no hierarchical path.  Level 0 would dump the whole subtree
// for no extra reach.
//
// The module and file are named after the top because one xsi/ directory can serve several tops,
// and a dumper naming a scope that is not elaborated is an error.
`timescale 1 ns / 1 ps

module vcd_dumper_rf_repeat_play;
    initial begin
        $dumpfile("rf_repeat_play_trace.vcd");
        $dumpvars(1, rf_repeat_play);
    end
endmodule
