// rf_pingpong_rx_top.v — GENERATED by waveflow (build/wrapper_gen.py::render_wrapper).
// DO NOT EDIT: regenerate instead.
//
// The design scope: the generated kernel `rf_pingpong_rx` plus the hand-written memories it
// reaches through `mode=bram` ports.  The kernel cannot contain them (Vitis turns an array
// shared between two tasks into a synchronizing PIPO channel, and refuses one port used both
// ways), so they live beside it and this module is what joins them.
//
// From outside this looks like a kernel with only its AXI-Stream ports — the memories are
// internal and invisible to any testbench.  It is also what a resource estimate should
// count: csynth of the kernel alone never sees them.
`timescale 1ns/1ps
module rf_pingpong_rx_top (
    input  ap_clk,
    input  ap_rst_n,
    input  [63:0] samp_in_TDATA,
    input  samp_in_TVALID,
    output samp_in_TREADY,
    output [63:0] w_out_TDATA,
    output w_out_TVALID,
    input  w_out_TREADY,
    output [7:0] w_out_TKEEP,
    output [7:0] w_out_TSTRB,
    output w_out_TLAST
);

    wire [31:0] buf_w_addr_a;
    wire [63:0] buf_w_din_a;
    wire [63:0] buf_w_dout_a;
    wire buf_w_en_a;
    wire [7:0] buf_w_we_a;
    wire [63:0] buf_w_dout_b;
    wire [31:0] buf_r_addr_a;
    wire [63:0] buf_r_din_a;
    wire [63:0] buf_r_dout_a;
    wire buf_r_en_a;
    wire [7:0] buf_r_we_a;
    wire [63:0] buf_r_dout_b;

    rf_pingpong_rx kernel (
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        .samp_in_TDATA(samp_in_TDATA),
        .samp_in_TVALID(samp_in_TVALID),
        .samp_in_TREADY(samp_in_TREADY),
        .w_out_TDATA(w_out_TDATA),
        .w_out_TVALID(w_out_TVALID),
        .w_out_TREADY(w_out_TREADY),
        .w_out_TKEEP(w_out_TKEEP),
        .w_out_TSTRB(w_out_TSTRB),
        .w_out_TLAST(w_out_TLAST),
        .buf_w_Addr_A(buf_w_addr_a),
        .buf_w_Din_A(buf_w_din_a),
        .buf_w_Dout_A(buf_w_dout_a),
        .buf_w_EN_A(buf_w_en_a),
        .buf_w_WEN_A(buf_w_we_a),
        .buf_w_Addr_B(),
        .buf_w_EN_B(),
        .buf_w_Din_B(),
        .buf_w_WEN_B(),
        .buf_w_Dout_B(buf_w_dout_b),
        .buf_w_Clk_A(),
        .buf_w_Clk_B(),
        .buf_w_Rst_A(),
        .buf_w_Rst_B(),
        .buf_r_Addr_A(buf_r_addr_a),
        .buf_r_Din_A(buf_r_din_a),
        .buf_r_Dout_A(buf_r_dout_a),
        .buf_r_EN_A(buf_r_en_a),
        .buf_r_WEN_A(buf_r_we_a),
        .buf_r_Addr_B(),
        .buf_r_EN_B(),
        .buf_r_Din_B(),
        .buf_r_WEN_B(),
        .buf_r_Dout_B(buf_r_dout_b),
        .buf_r_Clk_A(),
        .buf_r_Clk_B(),
        .buf_r_Rst_A(),
        .buf_r_Rst_B()
    );

    bram_t2p #(.DW(64), .AW(8)) mem (
        .clk(ap_clk),
        .a_addr(buf_w_addr_a >> 3),
        .a_din(buf_w_din_a),
        .a_dout(buf_w_dout_a),
        .a_en(buf_w_en_a),
        .a_we(|buf_w_we_a),
        .b_addr(buf_r_addr_a >> 3),
        .b_din(buf_r_din_a),
        .b_dout(buf_r_dout_a),
        .b_en(buf_r_en_a),
        .b_we(|buf_r_we_a)
    );

    // The B half, for each bram interface that HAS one: `storage_type=ram_1wnr`
    // emits a full A/B pair whether or not the kernel uses both, so its Dout INPUT
    // must be driven.  A `ram_1p` port (a read-write one) declares no B half at all.
    assign buf_w_dout_b = 64'd0;
    assign buf_r_dout_b = 64'd0;
endmodule
