#ifndef WAVEFLOW_GEN_BRAM_ACCESS_TB_HARNESS_H
#define WAVEFLOW_GEN_BRAM_ACCESS_TB_HARNESS_H
// bram_access_tb_harness.h -- GENERATED by waveflow (build/composite_gen.py::render_tb_harness)
// from the bram_access testbench graph.  DO NOT EDIT: regenerate instead.
//
// The derivable half of an XSI testbench: which models drive which RTL ports, the three
// per-cycle phases, and the run loop.  What it deliberately does NOT contain is the TEST --
// what goes in memory and what is checked afterwards.  Those are the golden, and the graph
// cannot know them.
#include <cstdint>
#include <string>
#include <vector>
#include "xsi_bfm.h"
#include "bram_access_ports.h"

namespace bram_access_tb {

using namespace wfbfm;

struct Harness {
    // Declaration order IS construction order: the sim must exist before any model can
    // resolve a port against it, and a shared arena before the slaves that serve from it.
    XsiSim sim;
    AxisMaster cmd_w;
    AxisMaster data_w;
    AxisSlave resp_w;
    AxisMaster cmd_r;
    AxisSlave data_r;
    AxisSlave resp_r;
    // Every participant by base pointer, in construction order (shared arenas
    // first): the one list the five lifecycle phases iterate, mirroring how
    // Simulation.run_sim() drives its SimObjs.
    std::vector<wfbfm::XsiSimObj*> participants_;

    explicit Harness(const std::string& wdb)
      : sim(bram_access_ports::DESIGN_DLL, wdb),
        cmd_w(sim.dut(), bram_access_ports::cmd_w, {}),
        data_w(sim.dut(), bram_access_ports::data_w, {}),
        resp_w(sim.dut(), bram_access_ports::resp_w),
        cmd_r(sim.dut(), bram_access_ports::cmd_r, {}),
        data_r(sim.dut(), bram_access_ports::data_r),
        resp_r(sim.dut(), bram_access_ports::resp_r)
    {
        // Every TB-driven input the models above do not themselves drive.  Absent
        // names are skipped; an undriven input is X, and X on a handshake hangs.
        sim.pin_low(bram_access_ports::ZERO_PORTS, bram_access_ports::ZERO_PORTS_N);
        // Register participants for the lifecycle phases (shared arenas first, so a
        // memory's pre_sim runs before the models that serve from it).
        participants_.push_back(&cmd_w);
        participants_.push_back(&data_w);
        participants_.push_back(&resp_w);
        participants_.push_back(&cmd_r);
        participants_.push_back(&data_r);
        participants_.push_back(&resp_r);
        // Init-time config (DynParams): each is a knob the pysim participant
        // carries, emitted here as a member assignment (e.g. a model's bundle).
        cmd_w.in_bundle = "vectors/cmd_w";
        data_w.in_bundle = "vectors/data_w";
        resp_w.out_bundle = "vectors/resp_w";
        cmd_r.in_bundle = "vectors/cmd_r";
        data_r.out_bundle = "vectors/data_r";
        resp_r.out_bundle = "vectors/resp_r";
    }
    void pre_sim() { for (auto* p : participants_) p->pre_sim(); }
    void sample() { for (auto* p : participants_) p->sample(); }
    void update() { for (auto* p : participants_) p->update(); }
    void drive() { for (auto* p : participants_) p->drive(); }
    void post_sim() { for (auto* p : participants_) p->post_sim(); }

    /// Run exactly *n_cycles*.  No early termination: see the note in the file header --
    /// nothing blocks, so the DUT's pipelining survives by construction.  Undersize n and
    /// the caller's own completion check fails loudly rather than passing quietly.
    void run(long n_cycles) {
        pre_sim();                       // participants seed memory / load vectors
        sim.reset([this]{ drive(); });
        for (long c = 0; c < n_cycles; ++c) {
            sim.clock_low();
            sample();
            sim.clock_high();
            update();
            drive();
        }
        post_sim();                      // participants dump results / collect metrics
    }

    void close() { sim.close(); }
};

}  // namespace bram_access_tb

#endif  // WAVEFLOW_GEN_BRAM_ACCESS_TB_HARNESS_H
