#ifndef WAVEFLOW_GEN_INTERLEAVER_INBAND_VECTORS_H
#define WAVEFLOW_GEN_INTERLEAVER_INBAND_VECTORS_H
// interleaver_inband_vectors.h -- GENERATED by waveflow (build/composite_gen.py::render_vectors_h).
// DO NOT EDIT: regenerate instead.  Plain C++ (no HLS types) so a host-compiled testbench
// can include it.  Command words are the output of the schema's own serialize() -- the
// testbench never re-implements a packing rule, so it cannot drift from the schema.
// Derived from the InterleaverInbandTB graph (examples/interleaver/interleaver_inband_sim.py)
// -- the same class the pysim golden runs.  The command words + P/X arena + golden ride the
// burst bundles under xsi/vectors/, written by write_xsi_bundles.
#include <cstdint>

namespace interleaver_inband_vectors {

static const int MEM_DW = 64;
static const int MEM_NW = 4672;
static const int NUM_CMDS = 12;
static const int DONE_WORDS = 1;

}  // namespace interleaver_inband_vectors

#endif  // WAVEFLOW_GEN_INTERLEAVER_INBAND_VECTORS_H
