// interleaver_inband_bfm_tb.cpp -- GENERATED by waveflow (build/composite_gen.py::render_tb_main)
// from the interleaver_inband testbench graph.  DO NOT EDIT: regenerate instead.
//
// The whole TB main: construct the generated harness, run a fixed number of cycles (the
// participants load their input bundles in pre_sim and dump their outputs in post_sim), then
// close.  No golden here -- correctness is checked in Python from the dumped output bundles.
#include "interleaver_inband_tb_harness.h"

int main() {
    interleaver_inband_tb::Harness h("interleaver_inband_bfm.wdb");
    h.run(wfbfm::run_param("n_cycles", 20000));
    h.close();
    return 0;
}
