#ifndef WAVEFLOW_GEN_MEM_R_STREAM_PORTS_H
#define WAVEFLOW_GEN_MEM_R_STREAM_PORTS_H
// mem_r_stream_ports.h -- GENERATED by waveflow (build/composite_gen.py::render_ports_h) from the SAME
// TopSpec that emits mem_r_stream's interface pragmas.  DO NOT EDIT: regenerate instead.
// One spec, two consumers -- so a testbench cannot drift from the kernel it drives.

namespace mem_r_stream_ports {

static const char* const TOP        = "mem_r_stream";

// xelab -dll emits the platform's native shared library, so the name differs by OS.  The
// conditional lives in the generated header rather than in the generator so ONE emitted
// header serves a Windows and a Linux build of the same testbench.
#ifdef _WIN32
static const char* const DESIGN_DLL = "xsim.dir/mem_r_stream/xsimk.dll";
#else
static const char* const DESIGN_DLL = "xsim.dir/mem_r_stream/xsimk.so";
#endif

static const char* const s_cmd    = "s_cmd";   // axis_in
static const char* const m_mem    = "m_axi_gmem0";   // maxi_read on gmem0
static const char* const m_out    = "m_out";   // axis_out

// Every TB-driven input the interface models above do not themselves drive.  Absent names
// are skipped at bind time (XsiSim::pin_low), so this may name channels a given kernel
// does not expose.
static const char* const ZERO_PORTS[] = {
    "s_axi_control_AWVALID",
    "s_axi_control_AWADDR",
    "s_axi_control_WVALID",
    "s_axi_control_WDATA",
    "s_axi_control_WSTRB",
    "s_axi_control_ARVALID",
    "s_axi_control_ARADDR",
    "s_axi_control_RREADY",
    "s_axi_control_BREADY",
    "m_axi_gmem0_AWREADY",
    "m_axi_gmem0_WREADY",
    "m_axi_gmem0_BVALID",
    "m_axi_gmem0_BRESP",
    "m_axi_gmem0_BID",
    "m_axi_gmem0_BUSER",
    "m_axi_gmem0_RRESP",
    "m_axi_gmem0_RID",
    "m_axi_gmem0_RUSER",
};
static const int ZERO_PORTS_N = (int)(sizeof(ZERO_PORTS)/sizeof(ZERO_PORTS[0]));

}  // namespace mem_r_stream_ports

#endif  // WAVEFLOW_GEN_MEM_R_STREAM_PORTS_H
