#ifndef WAVEFLOW_GEN_RF_LOOPBACK_IQ_TB_HARNESS_H
#define WAVEFLOW_GEN_RF_LOOPBACK_IQ_TB_HARNESS_H
// rf_loopback_iq_tb_harness.h -- GENERATED by waveflow (build/composite_gen.py::render_tb_harness)
// from the rf_pass_through testbench graph.  DO NOT EDIT: regenerate instead.
//
// The derivable half of an XSI testbench: which models drive which RTL ports, the three
// per-cycle phases, and the run loop.  What it deliberately does NOT contain is the TEST --
// what goes in memory and what is checked afterwards.  Those are the golden, and the graph
// cannot know them.
#include <cstdint>
#include <string>
#include <vector>
#include "xsi_bfm.h"
#include "xsi_channel.h"
#include "xsi_rfdc.h"
#include "xsi_rf_block.h"
#include "rf_pass_through_ports.h"

namespace rf_loopback_iq_tb {

using namespace wfbfm;

struct Harness {
    // Declaration order IS construction order: the sim must exist before any model can
    // resolve a port against it, and a shared arena before the slaves that serve from it.
    XsiSim sim;
    // Behavioral edges. Declared BEFORE their peer models, so each channel's
    // sample() commits before any peer observes it -- which is what makes the
    // transfer independent of participant order (see xsi_channel.h).
    BlockChannel<RfBlockMsg> xsi_tb_iq_adc_if;
    BlockChannel<RfBlockMsg> xsi_tb_iq_dac_if;
    RfdcAdcMaster s_in;
    RfdcDacSlave s_out;
    RfFileSource xsi_tb_iq_adc_if_tx;
    RfFileSink xsi_tb_iq_dac_if_rx;
    // Every participant by base pointer, in construction order (shared arenas
    // first): the one list the five lifecycle phases iterate, mirroring how
    // Simulation.run_sim() drives its SimObjs.
    std::vector<wfbfm::XsiSimObj*> participants_;

    explicit Harness(const std::string& wdb)
      : sim(rf_pass_through_ports::DESIGN_DLL, wdb),
        xsi_tb_iq_adc_if(2),
        xsi_tb_iq_dac_if(2),
        s_in(sim.dut(), rf_pass_through_ports::s_in, xsi_tb_iq_adc_if, RfdcFormat{14, 2, 1.0, 16, 2, RFDC_IQ, RFDC_I_LOW}, 0.256),
        s_out(sim.dut(), rf_pass_through_ports::s_out, xsi_tb_iq_dac_if, RfdcFormat{14, 2, 1.0, 16, 2, RFDC_IQ, RFDC_I_LOW}, 0.256, 512),
        xsi_tb_iq_adc_if_tx(xsi_tb_iq_adc_if, 512, 1),
        xsi_tb_iq_dac_if_rx(xsi_tb_iq_dac_if, 1)
    {
        // Every TB-driven input the models above do not themselves drive.  Absent
        // names are skipped; an undriven input is X, and X on a handshake hangs.
        sim.pin_low(rf_pass_through_ports::ZERO_PORTS, rf_pass_through_ports::ZERO_PORTS_N);
        // Register participants for the lifecycle phases (shared arenas first, so a
        // memory's pre_sim runs before the models that serve from it).
        participants_.push_back(&xsi_tb_iq_adc_if);
        participants_.push_back(&xsi_tb_iq_dac_if);
        participants_.push_back(&s_in);
        participants_.push_back(&s_out);
        participants_.push_back(&xsi_tb_iq_adc_if_tx);
        participants_.push_back(&xsi_tb_iq_dac_if_rx);
        // Init-time config (DynParams): each is a knob the pysim participant
        // carries, emitted here as a member assignment (e.g. a model's bundle).
        xsi_tb_iq_adc_if_tx.in_bundle = "vectors/rf_in_iq";
        xsi_tb_iq_dac_if_rx.out_bundle = "vectors/rf_out_iq";
    }
    void pre_sim() { for (auto* p : participants_) p->pre_sim(); }
    void sample() { for (auto* p : participants_) p->sample(); }
    void update() { for (auto* p : participants_) p->update(); }
    void drive() { for (auto* p : participants_) p->drive(); }
    void post_sim() { for (auto* p : participants_) p->post_sim(); }

    /// Run exactly *n_cycles*.  No early termination: see the note in the file header --
    /// nothing blocks, so the DUT's pipelining survives by construction.  Undersize n and
    /// the caller's own completion check fails loudly rather than passing quietly.
    void run(long n_cycles) {
        pre_sim();                       // participants seed memory / load vectors
        sim.reset([this]{ drive(); });
        for (long c = 0; c < n_cycles; ++c) {
            sim.clock_low();
            sample();
            sim.clock_high();
            update();
            drive();
        }
        post_sim();                      // participants dump results / collect metrics
    }

    void close() { sim.close(); }
};

}  // namespace rf_loopback_iq_tb

#endif  // WAVEFLOW_GEN_RF_LOOPBACK_IQ_TB_HARNESS_H
