// rf_pass_through_bfm_tb.cpp -- GENERATED by waveflow (build/composite_gen.py::render_tb_main)
// from the rf_pass_through testbench graph.  DO NOT EDIT: regenerate instead.
//
// The whole TB main: construct the generated harness, run a fixed number of cycles (the
// participants load their input bundles in pre_sim and dump their outputs in post_sim), then
// close.  No golden here -- correctness is checked in Python from the dumped output bundles.
#include "rf_pass_through_tb_harness.h"

int main() {
    rf_pass_through_tb::Harness h("rf_pass_through_bfm.wdb");
    h.run(2000);
    h.close();
    return 0;
}
