#ifndef WAVEFLOW_GEN_RF_PASS_THROUGH_2CH_PORTS_H
#define WAVEFLOW_GEN_RF_PASS_THROUGH_2CH_PORTS_H
// rf_pass_through_2ch_ports.h -- GENERATED by waveflow (build/composite_gen.py::render_ports_h) from the SAME
// TopSpec that emits rf_pass_through_2ch's interface pragmas.  DO NOT EDIT: regenerate instead.
// One spec, two consumers -- so a testbench cannot drift from the kernel it drives.

namespace rf_pass_through_2ch_ports {

static const char* const TOP        = "rf_pass_through_2ch";

// xelab -dll emits the platform's native shared library, so the name differs by OS.  The
// conditional lives in the generated header rather than in the generator so ONE emitted
// header serves a Windows and a Linux build of the same testbench.
#ifdef _WIN32
static const char* const DESIGN_DLL = "xsim.dir/rf_pass_through_2ch/xsimk.dll";
#else
static const char* const DESIGN_DLL = "xsim.dir/rf_pass_through_2ch/xsimk.so";
#endif

static const char* const s_in_0   = "s_in_0";   // axis_in
static const char* const s_out_0  = "s_out_0";   // axis_out
static const char* const s_in_1   = "s_in_1";   // axis_in
static const char* const s_out_1  = "s_out_1";   // axis_out

// Every TB-driven input the interface models above do not themselves drive.  Absent names
// are skipped at bind time (XsiSim::pin_low), so this may name channels a given kernel
// does not expose.
static const char* const ZERO_PORTS[] = {
};
static const int ZERO_PORTS_N = (int)(sizeof(ZERO_PORTS)/sizeof(ZERO_PORTS[0]));

}  // namespace rf_pass_through_2ch_ports

#endif  // WAVEFLOW_GEN_RF_PASS_THROUGH_2CH_PORTS_H
