#ifndef WAVEFLOW_GEN_MEM_COPY_VECTORS_H
#define WAVEFLOW_GEN_MEM_COPY_VECTORS_H
// mem_copy_vectors.h -- GENERATED by waveflow (build/composite_gen.py::render_vectors_h).
// DO NOT EDIT: regenerate instead.  Plain C++ (no HLS types) so a host-compiled testbench
// can include it.  Command words are the output of the schema's own serialize() -- the
// testbench never re-implements a packing rule, so it cannot drift from the schema.
// Derived from the MemCopyTB graph (examples/mem_copy/mem_copy_sim.py) built with
// XSI_JOBS -- the same class the pysim golden runs, instantiated with this scenario.
// CMD_WORDS = the driver's own commands, packed by CopyCmd.serialize(word_bw).
#include <cstdint>

namespace mem_copy_vectors {

static const int MEM_DW = 64;
static const int MEM_NW = 24640;
static const int N = 128;
static const int NUM_CMDS = 16;
static const int DONE_WORDS = 5;
static const int CMD_WORDS_PER_CMD = 2;

static const int SRC_W[16] = { 64, 192, 320, 448, 576, 704, 832, 960, 1088, 1216, 1344, 1472, 1600, 1728, 1856, 1984 };
static const int DST_W[16] = { 4096, 4224, 4352, 4480, 4608, 4736, 4864, 4992, 5120, 5248, 5376, 5504, 5632, 5760, 5888, 6016 };
static const uint64_t CMD_WORDS[32] = { 17592186044480ULL, 128ULL, 18141941858496ULL, 128ULL, 18691697672512ULL, 128ULL, 19241453486528ULL, 128ULL, 19791209300544ULL, 128ULL, 20340965114560ULL, 128ULL, 20890720928576ULL, 128ULL, 21440476742592ULL, 128ULL, 21990232556608ULL, 128ULL, 22539988370624ULL, 128ULL, 23089744184640ULL, 128ULL, 23639499998656ULL, 128ULL, 24189255812672ULL, 128ULL, 24739011626688ULL, 128ULL, 25288767440704ULL, 128ULL, 25838523254720ULL, 128ULL };

}  // namespace mem_copy_vectors

#endif  // WAVEFLOW_GEN_MEM_COPY_VECTORS_H
