#ifndef WAVEFLOW_GEN_MEM_COPY_TB_HARNESS_H
#define WAVEFLOW_GEN_MEM_COPY_TB_HARNESS_H
// mem_copy_tb_harness.h -- GENERATED by waveflow (build/composite_gen.py::render_tb_harness)
// from the mem_copy testbench graph.  DO NOT EDIT: regenerate instead.
//
// The derivable half of an XSI testbench: which models drive which RTL ports, the three
// per-cycle phases, and the run loop.  What it deliberately does NOT contain is the TEST --
// what goes in memory and what is checked afterwards.  Those are the golden, and the graph
// cannot know them.
#include <cstdint>
#include <string>
#include <vector>
#include "xsi_bfm.h"
#include "mem_copy_ports.h"

namespace mem_copy_tb {

using namespace wfbfm;

struct Harness {
    // Declaration order IS construction order: the sim must exist before any model can
    // resolve a port against it, and a shared arena before the slaves that serve from it.
    XsiSim sim;
    FlatMemory mem;
    AxisMaster s_cmd;
    AxiMmReadSlave m_in;
    AxiMmWriteSlave m_out;
    AxisSlave s_done;

    explicit Harness(const std::string& wdb, const std::vector<uint64_t>& cmd_words)
      : sim(mem_copy_ports::DESIGN_DLL, wdb),
        mem(24640, 8),
        s_cmd(sim.dut(), mem_copy_ports::s_cmd, cmd_words),
        m_in(sim.dut(), mem_copy_ports::m_in, mem),
        m_out(sim.dut(), mem_copy_ports::m_out, mem),
        s_done(sim.dut(), mem_copy_ports::s_done)
    {
        // Every TB-driven input the models above do not themselves drive.  Absent
        // names are skipped; an undriven input is X, and X on a handshake hangs.
        sim.pin_low(mem_copy_ports::ZERO_PORTS, mem_copy_ports::ZERO_PORTS_N);
    }
    void sample() { s_cmd.sample(); m_in.sample(); m_out.sample(); s_done.sample(); }
    void update() { s_cmd.update(); m_in.update(); m_out.update(); s_done.update(); }
    void drive() { s_cmd.drive(); m_in.drive(); m_out.drive(); s_done.drive(); }

    /// Run exactly *n_cycles*.  No early termination: see the note in the file header --
    /// nothing blocks, so the DUT's pipelining survives by construction.  Undersize n and
    /// the caller's own completion check fails loudly rather than passing quietly.
    void run(long n_cycles) {
        sim.reset([this]{ drive(); });
        for (long c = 0; c < n_cycles; ++c) {
            sim.clock_low();
            sample();
            sim.clock_high();
            update();
            drive();
        }
    }

    void close() { sim.close(); }
};

}  // namespace mem_copy_tb

#endif  // WAVEFLOW_GEN_MEM_COPY_TB_HARNESS_H
