#ifndef WAVEFLOW_GEN_MEM_COPY_VECTORS_H
#define WAVEFLOW_GEN_MEM_COPY_VECTORS_H
// mem_copy_vectors.h -- GENERATED by waveflow (build/composite_gen.py::render_vectors_h).
// DO NOT EDIT: regenerate instead.  Plain C++ (no HLS types) so a host-compiled testbench
// can include it.  Command words are the output of the schema's own serialize() -- the
// testbench never re-implements a packing rule, so it cannot drift from the schema.
// Derived from the MemCopyTB graph (examples/mem_copy/mem_copy_sim.py) built with
// XSI_JOBS -- the same class the pysim golden runs, instantiated with this scenario.
// The command words are no longer baked here: they are the burst bundle xsi/vectors/s_cmd
// that the harness loads in pre_sim -- written by write_mem_copy_xsi_bundles.
#include <cstdint>

namespace mem_copy_vectors {

static const int MEM_DW = 64;
static const int MEM_NW = 24640;
static const int N = 128;
static const int NUM_CMDS = 16;
static const int DONE_WORDS = 5;

static const int SRC_W[16] = { 64, 192, 320, 448, 576, 704, 832, 960, 1088, 1216, 1344, 1472, 1600, 1728, 1856, 1984 };
static const int DST_W[16] = { 4096, 4224, 4352, 4480, 4608, 4736, 4864, 4992, 5120, 5248, 5376, 5504, 5632, 5760, 5888, 6016 };

}  // namespace mem_copy_vectors

#endif  // WAVEFLOW_GEN_MEM_COPY_VECTORS_H
