// rf_blk_delay_top.v — GENERATED by waveflow (build/wrapper_gen.py::render_wrapper).
// DO NOT EDIT: regenerate instead.
//
// The design scope: the generated kernel `rf_blk_delay` plus the hand-written memories it
// reaches through `mode=bram` ports.  The kernel cannot contain them (Vitis turns an array
// shared between two tasks into a synchronizing PIPO channel, and refuses one port used both
// ways), so they live beside it and this module is what joins them.
//
// From outside this looks like a kernel with only its AXI-Stream ports — the memories are
// internal and invisible to any testbench.  It is also what a resource estimate should
// count: csynth of the kernel alone never sees them.
`timescale 1ns/1ps
module rf_blk_delay_top (
    input  ap_clk,
    input  ap_rst_n,
    input  [63:0] s_in_TDATA,
    input  s_in_TVALID,
    output s_in_TREADY,
    output [63:0] rx_resp_TDATA,
    output rx_resp_TVALID,
    input  rx_resp_TREADY,
    output [63:0] tx_resp_TDATA,
    output tx_resp_TVALID,
    input  tx_resp_TREADY,
    output [63:0] s_out_TDATA,
    output s_out_TVALID,
    input  s_out_TREADY
);

    wire [31:0] rx_buf_w_addr_a;
    wire [63:0] rx_buf_w_din_a;
    wire [63:0] rx_buf_w_dout_a;
    wire rx_buf_w_en_a;
    wire [7:0] rx_buf_w_we_a;
    wire [63:0] rx_buf_w_dout_b;
    wire [31:0] rx_buf_r_addr_a;
    wire [63:0] rx_buf_r_din_a;
    wire [63:0] rx_buf_r_dout_a;
    wire rx_buf_r_en_a;
    wire [7:0] rx_buf_r_we_a;
    wire [63:0] rx_buf_r_dout_b;
    wire [31:0] tx_buf_w_addr_a;
    wire [63:0] tx_buf_w_din_a;
    wire [63:0] tx_buf_w_dout_a;
    wire tx_buf_w_en_a;
    wire [7:0] tx_buf_w_we_a;
    wire [63:0] tx_buf_w_dout_b;
    wire [31:0] tx_buf_r_addr_a;
    wire [63:0] tx_buf_r_din_a;
    wire [63:0] tx_buf_r_dout_a;
    wire tx_buf_r_en_a;
    wire [7:0] tx_buf_r_we_a;
    wire [63:0] tx_buf_r_dout_b;

    rf_blk_delay kernel (
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        .s_in_TDATA(s_in_TDATA),
        .s_in_TVALID(s_in_TVALID),
        .s_in_TREADY(s_in_TREADY),
        .rx_resp_TDATA(rx_resp_TDATA),
        .rx_resp_TVALID(rx_resp_TVALID),
        .rx_resp_TREADY(rx_resp_TREADY),
        .tx_resp_TDATA(tx_resp_TDATA),
        .tx_resp_TVALID(tx_resp_TVALID),
        .tx_resp_TREADY(tx_resp_TREADY),
        .s_out_TDATA(s_out_TDATA),
        .s_out_TVALID(s_out_TVALID),
        .s_out_TREADY(s_out_TREADY),
        .rx_buf_w_Addr_A(rx_buf_w_addr_a),
        .rx_buf_w_Din_A(rx_buf_w_din_a),
        .rx_buf_w_Dout_A(rx_buf_w_dout_a),
        .rx_buf_w_EN_A(rx_buf_w_en_a),
        .rx_buf_w_WEN_A(rx_buf_w_we_a),
        .rx_buf_w_Addr_B(),
        .rx_buf_w_EN_B(),
        .rx_buf_w_Din_B(),
        .rx_buf_w_WEN_B(),
        .rx_buf_w_Dout_B(rx_buf_w_dout_b),
        .rx_buf_w_Clk_A(),
        .rx_buf_w_Clk_B(),
        .rx_buf_w_Rst_A(),
        .rx_buf_w_Rst_B(),
        .rx_buf_r_Addr_A(rx_buf_r_addr_a),
        .rx_buf_r_Din_A(rx_buf_r_din_a),
        .rx_buf_r_Dout_A(rx_buf_r_dout_a),
        .rx_buf_r_EN_A(rx_buf_r_en_a),
        .rx_buf_r_WEN_A(rx_buf_r_we_a),
        .rx_buf_r_Addr_B(),
        .rx_buf_r_EN_B(),
        .rx_buf_r_Din_B(),
        .rx_buf_r_WEN_B(),
        .rx_buf_r_Dout_B(rx_buf_r_dout_b),
        .rx_buf_r_Clk_A(),
        .rx_buf_r_Clk_B(),
        .rx_buf_r_Rst_A(),
        .rx_buf_r_Rst_B(),
        .tx_buf_w_Addr_A(tx_buf_w_addr_a),
        .tx_buf_w_Din_A(tx_buf_w_din_a),
        .tx_buf_w_Dout_A(tx_buf_w_dout_a),
        .tx_buf_w_EN_A(tx_buf_w_en_a),
        .tx_buf_w_WEN_A(tx_buf_w_we_a),
        .tx_buf_w_Addr_B(),
        .tx_buf_w_EN_B(),
        .tx_buf_w_Din_B(),
        .tx_buf_w_WEN_B(),
        .tx_buf_w_Dout_B(tx_buf_w_dout_b),
        .tx_buf_w_Clk_A(),
        .tx_buf_w_Clk_B(),
        .tx_buf_w_Rst_A(),
        .tx_buf_w_Rst_B(),
        .tx_buf_r_Addr_A(tx_buf_r_addr_a),
        .tx_buf_r_Din_A(tx_buf_r_din_a),
        .tx_buf_r_Dout_A(tx_buf_r_dout_a),
        .tx_buf_r_EN_A(tx_buf_r_en_a),
        .tx_buf_r_WEN_A(tx_buf_r_we_a),
        .tx_buf_r_Addr_B(),
        .tx_buf_r_EN_B(),
        .tx_buf_r_Din_B(),
        .tx_buf_r_WEN_B(),
        .tx_buf_r_Dout_B(tx_buf_r_dout_b),
        .tx_buf_r_Clk_A(),
        .tx_buf_r_Clk_B(),
        .tx_buf_r_Rst_A(),
        .tx_buf_r_Rst_B()
    );

    bram_t2p #(.DW(64), .AW(10)) _codegen_rx_mem (
        .clk(ap_clk),
        .a_addr(rx_buf_w_addr_a >> 3),
        .a_din(rx_buf_w_din_a),
        .a_dout(rx_buf_w_dout_a),
        .a_en(rx_buf_w_en_a),
        .a_we(|rx_buf_w_we_a),
        .b_addr(rx_buf_r_addr_a >> 3),
        .b_din(rx_buf_r_din_a),
        .b_dout(rx_buf_r_dout_a),
        .b_en(rx_buf_r_en_a),
        .b_we(|rx_buf_r_we_a)
    );

    bram_t2p #(.DW(64), .AW(11)) _codegen_tx_mem (
        .clk(ap_clk),
        .a_addr(tx_buf_w_addr_a >> 3),
        .a_din(tx_buf_w_din_a),
        .a_dout(tx_buf_w_dout_a),
        .a_en(tx_buf_w_en_a),
        .a_we(|tx_buf_w_we_a),
        .b_addr(tx_buf_r_addr_a >> 3),
        .b_din(tx_buf_r_din_a),
        .b_dout(tx_buf_r_dout_a),
        .b_en(tx_buf_r_en_a),
        .b_we(|tx_buf_r_we_a)
    );

    // The B half, for each bram interface that HAS one: `storage_type=ram_1wnr`
    // emits a full A/B pair whether or not the kernel uses both, so its Dout INPUT
    // must be driven.  A `ram_1p` port (a read-write one) declares no B half at all.
    assign rx_buf_w_dout_b = 64'd0;
    assign rx_buf_r_dout_b = 64'd0;
    assign tx_buf_w_dout_b = 64'd0;
    assign tx_buf_r_dout_b = 64'd0;
endmodule
