"""build.py — code generation for the CG hardware blocks: headers, types, composite tops, csynth.

Steps 4.3 onward of ``plans/mimo_cg/mimo_cg_paper_sims.md``.  For one configuration it writes,
under a build directory (default ``examples/mimo_cg/hw/build/<top>_<config>/``, gitignored):

* ``include/`` — the framework headers (streamutils, memmgr, the mem-stream bodies), the schema
  headers (the commands and descriptors), the generated array utils of the memory element types,
  the generated ``cg_types.h``, and copies of the hand-written task bodies from ``hw/cpp/``;
* ``gen/<top>.cpp`` — the ``ap_ctrl_none`` composite top, one ``hls::task`` per child, walked
  from the Python graph;
* ``<top>.tcl`` — csynth for ``xczu48dr-ffvg1517-2-e`` at 4 ns;
* ``xsi/<top>_ports.h`` — the port map the XSI harness includes.

``cg_types.h`` holds, in ``namespace cg``, the register and exact-accumulator ``ap_fixed`` types of
the format set (the renderer the C++ reference uses) and one small struct per memory element type
(``a_mem``, ``b_mem``, ``s_mem``, ``p_mem``, ``x_mem``) that forwards to its generated array utils:
a namespace cannot be a template argument, a struct can.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from examples.mimo_cg.hw.common import (
    DEFAULT_MEM_DW,
    DEFAULT_N,
    CgCmd,
    CgDesc,
    CgIterCmd,
    IterOpField,
    hw_format,
    mem_format,
    render_typedefs,
)
from examples.mimo_cg.mimo_cg_fixed import CgFormats
from waveflow.build.build import BuildConfig, BuildDag
from waveflow.build.composite_gen import (
    GEN_DIR,
    INCLUDE_DIR,
    composite_top_spec,
    render_ports_h,
    render_rtl_f,
    render_tb_harness,
    render_tb_main,
    render_tcl,
    render_top,
    render_vectors_h,
    tb_top_spec,
)
from waveflow.build.elaborate import elaborate
from waveflow.build.streamutils import (
    MemMgrStep,
    MemStreamStep,
    StreamUtilsStep,
    XsiHarnessStep,
)
from waveflow.hw.arrayutils import (
    _array_utils_filename,
    _array_utils_namespace,
    gen_array_utils,
)
from waveflow.hw.complexfield import ComplexField
from waveflow.hw.dataschema import DataSchemaStep
from waveflow.hw.fixpoint import FixedField
from waveflow.hw.mem_stream import WORD_BW_SUPPORTED, MemRCmd, MemWCmd
from waveflow.toolchain import toolchain

HW_DIR = Path(__file__).resolve().parent
CPP_DIR = HW_DIR / "cpp"
BUILD_ROOT = HW_DIR / "build"
#: The study's target (gate 4.0): the RFSoC 4x2's part at 250 MHz.
PART = "xczu48dr-ffvg1517-2-e"
PERIOD_NS = 4
#: Registers that travel through memory, by the name of their ``*_mem`` struct.
MEM_REGISTERS = ("A", "B", "S", "P", "X")


def mem_elem_type(fmt) -> type[ComplexField]:
    """The memory element type of a register: ``ComplexField[FixedField<16, I>]`` (see
    :func:`~examples.mimo_cg.hw.common.mem_format`)."""
    m = mem_format(fmt)
    inner = FixedField.specialize(
        m.W, m.int_bits, m.signed, m.q_mode, m.o_mode, include_dir=INCLUDE_DIR
    )
    return ComplexField.specialize(inner, include_dir=INCLUDE_DIR)


def render_types_h(formats: CgFormats, K: int) -> str:
    """``cg_types.h``: the register and accumulator types, and the memory element structs."""
    includes, structs = [], []
    for reg in MEM_REGISTERS:
        elem = mem_elem_type(getattr(formats, reg))
        ns = _array_utils_namespace(elem)
        inc = f'#include "{_array_utils_filename(elem)}"'
        if inc not in includes:
            includes.append(inc)
        structs.append(f"""struct {reg.lower()}_mem {{
    typedef {ns}::value_type value_type;
    template <int WBW> static constexpr int lane_capacity() {{ return {ns}::lane_capacity<WBW>(); }}
    template <int WBW> static void read_framed_stream_lane(
        hls::stream<streamutils::framed_word<WBW> >& s, value_type* dst, int n,
        streamutils::tlast_status& tl) {{
#pragma HLS INLINE
        {ns}::read_framed_stream_lane<WBW>(s, dst, n, tl);
    }}
    template <int WBW> static void write_framed_stream_lane(
        const value_type* src, hls::stream<streamutils::framed_word<WBW> >& s, bool tlast, int n) {{
#pragma HLS INLINE
        {ns}::write_framed_stream_lane<WBW>(src, s, tlast, n);
    }}
}};""")
    typedefs = render_typedefs(formats, K, indent="")
    return f"""// GENERATED by examples/mimo_cg/hw/build.py -- do not edit.
// The CG register and exact-accumulator types (K = {K}) and the memory element structs.
#ifndef MIMO_CG_TYPES_H
#define MIMO_CG_TYPES_H
#include <ap_fixed.h>
#include "hls_stream.h"
#include "streamutils_hls.h"
{chr(10).join(includes)}

namespace cg {{
{typedefs}

{chr(10).join(structs)}
}}  // namespace cg

#endif  // MIMO_CG_TYPES_H
"""


def gen_headers(config: BuildConfig, schemas, formats: CgFormats, K: int, mem_dw: int):
    """Framework headers, the schema headers, the memory element array utils and ``cg_types.h``
    into ``include/``, plus the hand-written task bodies copied from ``hw/cpp/``."""
    framed = {CgDesc, CgIterCmd, MemRCmd, MemWCmd}
    dag = BuildDag()
    dag.add(StreamUtilsStep(output_dir=INCLUDE_DIR))
    dag.add(MemMgrStep(output_dir=INCLUDE_DIR))
    dag.add(MemStreamStep(output_dir=INCLUDE_DIR))
    for cls in [IterOpField, *schemas]:
        dag.add(
            DataSchemaStep(
                cls,
                word_bw_supported=WORD_BW_SUPPORTED,
                include_dir=INCLUDE_DIR,
                framed=(cls in framed),
            )
        )
    dag.add(XsiHarnessStep(output_dir="xsi"))
    results = dag.run(config, force=True)
    failed = [n for n, r in results.items() if not r.success]
    if failed:
        raise RuntimeError(f"header generation failed: {failed}")
    seen = set()
    for reg in MEM_REGISTERS:
        elem = mem_elem_type(getattr(formats, reg))
        if elem not in seen:
            seen.add(elem)
            gen_array_utils(
                elem, [int(mem_dw)], cfg=config, streamutils_dir=INCLUDE_DIR
            )
    inc = Path(config.root_dir) / INCLUDE_DIR
    inc.mkdir(parents=True, exist_ok=True)
    (inc / "cg_types.h").write_text(render_types_h(formats, K), encoding="utf-8")
    for src in sorted(CPP_DIR.glob("*.h")):
        shutil.copyfile(src, inc / src.name)


def build_dir(top: str, K: int, fmt: int, **knobs) -> Path:
    """The default build directory of one configuration."""
    tag = "_".join(f"{k}{v}" for k, v in sorted(knobs.items()))
    return BUILD_ROOT / (f"{top}_k{K}_f{fmt}" + (f"_{tag}" if tag else ""))


def generate_top(
    comp_class, params: dict, top: str, out_dir: Path, schemas, mem_dw: int
) -> Path:
    """Generate one composite DUT: headers, the top, its csynth TCL and the XSI port map."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    config = BuildConfig(root_dir=out_dir, params={})
    formats = hw_format(int(params["fmt"]))
    gen_headers(config, schemas, formats, int(params["K"]), mem_dw)
    comp = elaborate(comp_class, params, name=top)
    spec = composite_top_spec(comp, width=mem_dw)
    gen = out_dir / GEN_DIR
    gen.mkdir(parents=True, exist_ok=True)
    cpp = gen / f"{spec.top_name}.cpp"
    cpp.write_text(render_top(spec), encoding="utf-8")
    (out_dir / f"{spec.top_name}.tcl").write_text(
        render_tcl(spec.top_name, part=PART, period_ns=PERIOD_NS), encoding="utf-8"
    )
    xsi = out_dir / "xsi"
    xsi.mkdir(parents=True, exist_ok=True)
    (xsi / f"{spec.top_name}_ports.h").write_text(
        render_ports_h(spec), encoding="utf-8"
    )
    return cpp


# --- csynth and the XSI run ----------------------------------------------------------------


def csynth(out_dir: Path, top: str) -> tuple[bool, Path, str]:
    """Run the generated ``<top>.tcl`` and write ``xsi/rtl_<top>.f`` with its source stamp (the
    record :func:`~waveflow.build.trace_steps.rtl_staleness` checks).  Returns
    ``(ok, report_dir, log)``; the log is also kept as ``csynth.log``."""
    out_dir = Path(out_dir)
    run = toolchain.run_vitis_hls(
        out_dir / f"{top}.tcl", work_dir=out_dir, capture_output=True
    )
    log = (run.stdout or "") + (run.stderr or "")
    (out_dir / "csynth.log").write_text(log, encoding="utf-8")
    report = out_dir / f"{top}_proj" / "solution1" / "syn" / "report"
    ok = run.returncode == 0 and (report / "csynth.xml").is_file()
    if ok:
        xsi = out_dir / "xsi"
        xsi.mkdir(parents=True, exist_ok=True)
        (xsi / f"rtl_{top}.f").write_text(render_rtl_f(top, out_dir), encoding="utf-8")
    return ok, report, log


def generate_tb(out_dir: Path, top: str, tb, sim) -> dict:
    """Generate the XSI testbench of ``top`` from its testbench graph ``tb`` and write the
    scenario bundles of the procedure ``sim`` (whose ``scenario()`` the Python run also uses).
    """
    from examples.mimo_cg.hw.common import CgDesc

    out_dir = Path(out_dir)
    xsi = out_dir / "xsi"
    xsi.mkdir(parents=True, exist_ok=True)
    w = int(tb.mem_dwidth)
    vectors = render_vectors_h(
        f"{top}_vectors",
        scalars={
            "MEM_DW": w,
            "MEM_NW": int(tb.mem.nwords_tot),
            "NUM_CMDS": len(tb.cmds),
            "DONE_WORDS": CgDesc.nwords_per_inst(w),
        },
        note="Derived from the testbench graph in examples/mimo_cg/hw/ -- the class the Python\n"
        "simulation runs.  Commands, memory image and golden ride the bundles under xsi/vectors/.",
    )
    (xsi / f"{top}_vectors.h").write_text(vectors, encoding="utf-8")
    spec = tb_top_spec(tb)
    (xsi / f"{top}_tb_harness.h").write_text(render_tb_harness(spec), encoding="utf-8")
    (xsi / f"{top}_bfm_tb.cpp").write_text(
        render_tb_main(spec, tb.n_cycles), encoding="utf-8"
    )
    sim.write_scenario(xsi)
    for name in ("out", "s_done"):  # never let a previous run's dump pass for this one
        d = xsi / "vectors" / name
        if d.exists():
            for f in d.iterdir():
                f.unlink()
    return sim.scenario()


def run_xsi(out_dir: Path, top: str):
    """Run the XSI harness (``run.sh`` / ``run.bat``) in ``<out_dir>/xsi``."""
    import subprocess

    from waveflow.build.trace_steps import xsi_runner_cmd

    xsi = Path(out_dir) / "xsi"
    return subprocess.run(
        xsi_runner_cmd(top, f"{top}_bfm_tb"),
        cwd=xsi,
        capture_output=True,
        text=True,
        check=False,
    )


def check_xsi_outputs(out_dir: Path, scenario: dict) -> list[int]:
    """Every expected output region of the XSI memory dump is exact, and every done arrived.

    Returns the cycle each done word arrived on ``s_done`` (the sink's ``cycles.bin``); the last
    is the run's time to last completion.
    """
    import numpy as np

    from waveflow.utils.burst_io import read_burst_bundle

    vdir = Path(out_dir) / "xsi" / "vectors"
    out = np.asarray(read_burst_bundle(vdir / "out")[0], np.uint64)
    for j, (off, exp) in enumerate(scenario["expected"]):
        got = out[off : off + len(exp)]
        if not np.array_equal(got, exp):
            bad = int(np.argmax(got != exp))
            raise AssertionError(
                f"RTL job {j} word {bad}: 0x{int(got[bad]):016x} != golden 0x{int(exp[bad]):016x}"
            )
    done = read_burst_bundle(vdir / "s_done")[0]
    assert len(done) == int(
        scenario["done_words"]
    ), f"s_done has {len(done)} words, expected {scenario['done_words']} (one per job)"
    cycles = np.fromfile(vdir / "s_done" / "cycles.bin", dtype="<u8")
    return [int(c) for c in cycles[: len(done)]]


# --- the vector unit -------------------------------------------------------------------------

VEC_TOP = "cg_vec_unit"


def generate_vec_unit(
    out_dir: Path | None = None,
    *,
    K: int = 4,
    N: int = DEFAULT_N,
    L: int = 4,
    fmt: int = 0,
    mem_dw: int = DEFAULT_MEM_DW,
    cmd_depth: int = 2,
    sob_depth: int = 2,
) -> Path:
    """Generate the ``CgVecUnit`` DUT for one configuration (see the module doc)."""
    from examples.mimo_cg.hw.vec import CgVecUnit, CgVecUnitCmd

    if out_dir is None:
        out_dir = build_dir(VEC_TOP, K, fmt)
    params = {
        "mem_dwidth": mem_dw,
        "K": K,
        "N": N,
        "L": L,
        "fmt": fmt,
        "cmd_depth": cmd_depth,
        "sob_depth": sob_depth,
    }
    schemas = [CgVecUnitCmd, CgDesc, CgIterCmd, CgCmd, MemRCmd, MemWCmd]
    return generate_top(CgVecUnit, params, VEC_TOP, Path(out_dir), schemas, mem_dw)


# --- the matrix multiply ---------------------------------------------------------------------

MM_TOP = "cg_mm_unit"


def generate_mm_unit(
    out_dir: Path | None = None,
    *,
    K: int = 4,
    N: int = DEFAULT_N,
    L: int = 4,
    R: int = 0,
    C: int = 4,
    cmul: int = 4,
    fmt: int = 0,
    mem_dw: int = DEFAULT_MEM_DW,
    cmd_depth: int = 2,
    sob_depth: int = 2,
) -> Path:
    """Generate the ``CgMmUnit`` DUT for one configuration (``R = 0`` means ``R = K``)."""
    from examples.mimo_cg.hw.mm import CgMmUnit, CgMmUnitCmd

    if out_dir is None:
        out_dir = build_dir(MM_TOP, K, fmt, cmul=cmul)
    params = {
        "mem_dwidth": mem_dw,
        "K": K,
        "N": N,
        "L": L,
        "R": R,
        "C": C,
        "cmul": cmul,
        "fmt": fmt,
        "cmd_depth": cmd_depth,
        "sob_depth": sob_depth,
    }
    schemas = [CgMmUnitCmd, CgDesc, CgIterCmd, CgCmd, MemRCmd, MemWCmd]
    return generate_top(CgMmUnit, params, MM_TOP, Path(out_dir), schemas, mem_dw)


# --- the integrated detector -----------------------------------------------------------------

DET_TOP = "cg_detector"


def generate_detector(
    out_dir: Path | None = None,
    *,
    K: int = 4,
    N: int = DEFAULT_N,
    L: int = 4,
    R: int = 0,
    C: int = 4,
    cmul: int = 4,
    fmt: int = 0,
    mem_dw: int = DEFAULT_MEM_DW,
    cmd_depth: int = 2,
    sob_depth: int = 2,
) -> Path:
    """Generate the ``CgDetector`` DUT for one configuration (``R = 0`` means ``R = K``)."""
    from examples.mimo_cg.hw.detector import CgDetector

    if out_dir is None:
        out_dir = build_dir(DET_TOP, K, fmt)
    params = {
        "mem_dwidth": mem_dw,
        "K": K,
        "N": N,
        "L": L,
        "R": R,
        "C": C,
        "cmul": cmul,
        "fmt": fmt,
        "cmd_depth": cmd_depth,
        "sob_depth": sob_depth,
    }
    schemas = [CgCmd, CgDesc, CgIterCmd, MemRCmd, MemWCmd]
    return generate_top(CgDetector, params, DET_TOP, Path(out_dir), schemas, mem_dw)
