"""csim.py — sequential Vitis C-simulation of a generated CG composite, against the Python scenario.

A check between the Python simulation and the RTL (step 4.3 onward of
``plans/mimo_cg/mimo_cg_paper_sims.md``): the hand-written task bodies, and the framework
mem-stream bodies around them, run as C++ on the scenario the Python simulation and the XSI run
use (the command words and the memory image), and every expected output region is compared.

**Why sequential.**  Calling the generated ``ap_ctrl_none`` top in C-sim runs every ``hls::task``
as a thread, and the Vitis 2024.1 C-sim model of ``hls::stream_of_blocks`` hands a block to its
reader at the writer's ``write_acquire`` — before the writer has filled it — and never reports
``full``.  So a threaded C-sim of a stream-of-blocks composite races: the matmul store read its
``S`` blocks before the systolic array had filled them.  The RTL has the real ping-pong semantics
(the reader waits for the writer's release) and is checked through XSI.  Here the testbench
instead declares the top's channels itself and calls each task body in dependency order, job by
job, the number of times the job needs (``reps``), so every block is complete before it is read and
the run is deterministic.  The channels and task calls are read off the generated top, so this runs
exactly the C++ that is synthesized.  ``m_in`` and ``m_out`` point at one arena, as the crossbar in
the XSI testbench does.
"""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np

from examples.mimo_cg.hw.build import PART, PERIOD_NS
from waveflow.build.composite_gen import GEN_DIR, INCLUDE_DIR
from waveflow.toolchain import toolchain

#: Firings per job of each task of the per-block composites, by task-function prefix, as C++
#: expressions in the job's ``nit``: one framer, load, block and store firing; one reader firing per
#: memory read and one writer firing per memory write.
VEC_REPS = {
    "cg_vec_rx_task": "1",
    "mem_r_stream_framed_task": "nit + 1",
    "cg_vec_load_task": "1",
    "cg_vec_task": "1",
    "cg_vec_store_task": "1",
    "mem_w_stream_framed_done_task": "nit + 1",
}
MM_REPS = {
    "cg_mm_rx_task": "1",
    "mem_r_stream_framed_task": "nit + 1",
    "cg_mm_load_task": "1",
    "cg_mm_task": "1",
    "cg_mm_store_task": "1",
    "mem_w_stream_framed_done_task": "nit + 1",
}

_TASK = re.compile(r"hls::task\s+\w+\((?P<fn>[\w:]+(?:<[^>]*>)?),\s*(?P<args>[^)]*)\);")


def render_seq_tb(top_cpp: str, top: str, mem_dw: int, reps: dict[str, str]) -> str:
    """The sequential testbench for the generated top ``top_cpp`` (its source text)."""
    includes = [ln for ln in top_cpp.splitlines() if ln.startswith("#include")]
    channels = [
        ln.strip().replace("hls_thread_local ", "")
        for ln in top_cpp.splitlines()
        if "hls_thread_local hls::stream" in ln
    ]
    calls = []
    for m in _TASK.finditer(top_cpp):
        fn, args = m.group("fn"), m.group("args")
        prefix = fn.split("<")[0]
        if prefix not in reps:
            raise KeyError(f"no firing count for task {prefix} of {top}")
        calls.append(f"        for (int r = 0; r < {reps[prefix]}; ++r) {fn}({args});")
    if len(calls) != len(reps):
        raise ValueError(f"{top}: found {len(calls)} tasks, expected {len(reps)}")
    nl = "\n"
    return f"""// GENERATED by examples/mimo_cg/hw/csim.py -- do not edit.
// Sequential C-sim of {top}: the top's channels and task bodies, fired in dependency order.
{nl.join(includes)}
#include <fstream>
#include <vector>

int main(int argc, char** argv) {{
    std::ifstream in(argv[1]);
    std::ofstream out(argv[2]);
    long ncmd, nmem, ndone, njobs;
    in >> ncmd >> nmem >> ndone >> njobs;
    std::vector<int> nits(njobs);
    for (long j = 0; j < njobs; ++j) in >> nits[j];
    hls::stream<ap_uint<{mem_dw}> > s_cmd, s_done;
    std::vector<ap_uint<{mem_dw}> > mem(nmem);
    unsigned long long v;
    for (long i = 0; i < ncmd; ++i) {{ in >> v; s_cmd.write(ap_uint<{mem_dw}>(v)); }}
    for (long i = 0; i < nmem; ++i) {{ in >> v; mem[i] = v; }}
    const ap_uint<{mem_dw}>* m_in = mem.data();
    ap_uint<{mem_dw}>* m_out = mem.data();
{nl.join("    " + c for c in channels)}
    for (long j = 0; j < njobs; ++j) {{
        const int nit = nits[j];
{nl.join(calls)}
    }}
    for (long i = 0; i < ndone && !s_done.empty(); ++i) out << "D " << (unsigned long long)s_done.read() << "\\n";
    for (long i = 0; i < nmem; ++i) out << (unsigned long long)mem[i] << "\\n";
    out << "CSIM_DONE\\n";
    return 0;
}}
"""


def render_csim_tcl(top: str) -> str:
    return f"""# GENERATED by examples/mimo_cg/hw/csim.py -- sequential C-simulation of {top}.
set cf "-I{INCLUDE_DIR}"
open_project -reset {top}_csim_proj
set_top {top}_seq_csim
add_files -tb csim_tb.cpp -cflags $cf
open_solution -reset solution1
set_part {{{PART}}}
create_clock -period {PERIOD_NS}
set d [file dirname [file normalize [info script]]]
if {{[catch {{csim_design -argv "[file join $d csim_in.txt] [file join $d csim_out.txt]"}} res]}} {{
    puts "WAVEFLOW_ERROR: C-simulation failed."
    puts $res
    exit 1
}}
puts "WAVEFLOW_SUCCESS: C-simulation finished."
exit 0
"""


def run_csim(
    build_dir: Path, top: str, mem_dw: int, scenario: dict, nits, reps: dict[str, str]
) -> dict:
    """Sequentially C-simulate the generated ``top`` in ``build_dir`` on ``scenario`` (see
    :meth:`~examples.mimo_cg.hw.vec.CgVecUnitSim.scenario`); ``nits`` gives each job's ``nit``.

    Returns ``{"ok", "mem", "done", "log"}``: ``ok`` is True when C-sim finished, every expected
    output region (``scenario["expected"]``, ``(offset, words)``) matches exactly and every done
    arrived; ``mem`` is the memory afterwards and ``done`` the done words.
    """
    build_dir = Path(build_dir)
    top_cpp = (build_dir / GEN_DIR / f"{top}.cpp").read_text(encoding="utf-8")
    cmd = np.concatenate([np.asarray(c, np.uint64) for c in scenario["cmd_words"]])
    mem = np.asarray(scenario["mem_in"], np.uint64)
    nits = [int(n) for n in nits]
    lines = [f"{len(cmd)} {len(mem)} {int(scenario['done_words'])} {len(nits)}"]
    lines += [str(n) for n in nits]
    lines += [str(int(x)) for x in cmd] + [str(int(x)) for x in mem]
    (build_dir / "csim_in.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (build_dir / "csim_tb.cpp").write_text(
        render_seq_tb(top_cpp, top, mem_dw, reps), encoding="utf-8"
    )
    tcl = build_dir / "csim.tcl"
    tcl.write_text(render_csim_tcl(top), encoding="utf-8")
    out = build_dir / "csim_out.txt"
    if out.exists():
        out.unlink()
    result = toolchain.run_vitis_hls(tcl, work_dir=build_dir, capture_output=True)
    log = (result.stdout or "") + (result.stderr or "")
    if not out.exists() or "CSIM_DONE" not in out.read_text(encoding="utf-8"):
        return {"ok": False, "mem": None, "done": [], "log": log}
    done, words = [], []
    for line in out.read_text(encoding="utf-8").splitlines():
        if line.startswith("D "):
            done.append(int(line[2:]))
        elif line and line != "CSIM_DONE":
            words.append(int(line))
    got = np.array(words, dtype=np.uint64)
    ok = len(done) == int(scenario["done_words"]) and all(
        np.array_equal(got[off : off + len(exp)], exp)
        for off, exp in scenario["expected"]
    )
    return {"ok": ok, "mem": got, "done": done, "log": log}
