"""rf_repeat_play_build.py — build the streaming transmitter: pysim -> gen-include -> csynth.

Two rungs, in the order a failure is cheapest to diagnose::

    pysim        the three Stage 1 assertions in SimPy (tests/examples/test_rf_repeat_play.py)
    gen_include  the four schema headers + the two hand-written hls::task bodies
    csynth       Vitis HLS over BOTH bodies, under hls::task, at the RF arc's part and clock

**What this build deliberately does NOT do: generate the composite top.**  ``RfTxStream`` is a
composite whose one internal edge is an
:class:`~waveflow.hw.reverse_stream.AckedStreamIF` — a *pair* of streams carrying **structs**
(``TaggedSamp`` and ``TxStatus``), not the ``ap_uint<W>`` word channels
:func:`~waveflow.build.composite_gen.derive_internal_edges` knows how to lower.  Teaching the
composite generator a new interface kind is real framework work and it is not Stage 1's; see the PR
body under *What I could not verify*.

So this file gates what it can gate honestly: it compiles and schedules the two bodies **as
``hls::task``s, against the real generated schema headers**, on the RF arc's own part and clock —
which is where the II that Stage 3 depends on is actually decided.  The top here is hand-written
(:data:`TOP_CPP`) and exists only to give csynth two tasks and their streams; it is not the design's
top and must not be mistaken for one.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import ClassVar

HERE = Path(__file__).resolve().parent

from waveflow.build.build import BuildConfig, BuildDag, BuildStep, SourceStep  # noqa: E402
from waveflow.build.composite_gen import (  # noqa: E402
    RFSOC4X2_PART,
    RFSOC4X2_PERIOD_NS,
)
from waveflow.build.streamutils import RfTxStreamStep, StreamUtilsStep  # noqa: E402
from waveflow.hw.dataschema import DataSchemaStep  # noqa: E402
from waveflow.toolchain import toolchain  # noqa: E402

from examples.rf_repeat_play.rf_repeat_play import (  # noqa: E402
    MAX_IN_FLIGHT,
    SAMP_BW,
    TX_STREAM_SCHEMA_CLASSES,
)

#: The csynth project's name.  Not a kernel name: see the module docstring.
TOP = "rf_tx_stream_tasks"
INCLUDE_DIR = "include"
GEN = "gen"

#: The gated geometry, stated rather than defaulted: ONE sample per word, 16-bit words on the
#: command / sample / response ports.  ``samp_per_word > 1`` is the throughput lever and is exercised
#: in pysim only.
SYNTH_SAMP_PER_WORD = 1
SYNTH_W = SAMP_BW * SYNTH_SAMP_PER_WORD

#: Statuses harvested per loader firing.  **Bounded and compile-time**, which is the whole point:
#: it unrolls into this many ``read_nb`` calls instead of the data-dependent ``while`` that costs the
#: BRAM loader its II.
STATUS_POLLS = MAX_IN_FLIGHT

#: Word widths the generated schema headers must support.  The command / response ports are
#: ``SYNTH_W``; the internal channels carry the **structs** rather than words, so they need only the
#: struct definition — but emitting 64 as well costs nothing and keeps the headers usable if an
#: internal edge is ever widened into a word channel.
WORD_BW_SUPPORTED = [SYNTH_W, 64]

#: The hand-written top.  ``ap_ctrl_none`` + ``hls::task`` is the free-running shape the whole RF arc
#: uses, and it is what makes the two bodies re-fire forever rather than being called once.
#:
#: The internal channels are declared at the depths the design's sizing rule names:
#: ``status`` at ``MAX_IN_FLIGHT`` (one status per accepted window, so it can never need more — and
#: a shallower one would let a status drop, which mis-pairs every later tid), and ``fwd`` deep enough
#: for the windows that may be in flight, because the loader's write is blocking and a shallower
#: channel would turn a scheduling decision into a stall.
TOP_CPP = f"""// {TOP}.cpp — GENERATED by rf_repeat_play_build.py.  Do not edit.
//
// A csynth harness for the two hand-written bodies of waveflow/hw/rf_tx_stream.py, NOT the design's
// top: RfTxStream's composite lowering is not built yet (see the build script's docstring).  What it
// gates is exactly what a top would gate about these bodies — that they compile against the real
// generated schema headers, that Vitis accepts them as hls::task bodies, and what II it achieves on
// the RF arc's part and clock.
#include "hls_task.h"
#include "hls_stream.h"
#include <ap_int.h>

#include "rf_tx_cmd.h"
#include "rf_tx_resp.h"
#include "rf_tx_status.h"
#include "rf_tagged_samp.h"
#include "rf_tx_loader_task.h"
#include "rf_tx_player_task.h"

#define W       {SYNTH_W}
#define SPW     {SYNTH_SAMP_PER_WORD}
#define MAXIF   {MAX_IN_FLIGHT}
#define POLLS   {STATUS_POLLS}
#define IDX_W   16

void {TOP}(hls::stream<ap_uint<W> >& cmd_in, hls::stream<ap_uint<W> >& samp_in,
           hls::stream<ap_uint<W> >& resp_out, hls::stream<ap_uint<W> >& samp_out) {{
#pragma HLS interface ap_ctrl_none port=return
#pragma HLS interface axis port=cmd_in
#pragma HLS interface axis port=samp_in
#pragma HLS interface axis port=resp_out
#pragma HLS interface axis port=samp_out
#pragma HLS dataflow

    hls_thread_local hls::stream<TaggedSamp, 512> fwd;
    hls_thread_local hls::stream<TxStatus, MAXIF> status;

    hls_thread_local hls::task loader(rf_tx_loader_task<W, SPW, MAXIF, POLLS, IDX_W>,
                                      cmd_in, samp_in, fwd, resp_out, status);
    hls_thread_local hls::task player(rf_tx_player_task<W, SPW, IDX_W>,
                                      fwd, samp_out, status);
}}
"""

TCL = f"""# {TOP}.tcl — GENERATED by rf_repeat_play_build.py.  Do not edit.
#
# The RF arc's part and clock, so the numbers here are comparable to every other gate in it:
# xczu48dr-ffvg1517-2-e at {RFSOC4X2_PERIOD_NS} ns.
open_project -reset {TOP}_proj
set_top {TOP}
add_files {GEN}/{TOP}.cpp -cflags "-I{INCLUDE_DIR}"
open_solution -reset -flow_target vitis solution1
set_part {RFSOC4X2_PART}
create_clock -period {RFSOC4X2_PERIOD_NS} -name default

# THE RESET TRAP, CLOSED HERE RATHER THAN IN THE BODIES -- and that placement is measured, not
# assumed.  An hls::task that writes before it reads advances its state registers during reset,
# because a `static x = 0` becomes a simulation initial value in the RTL and its update is emitted
# with no ap_rst term (reference-hls-task-reset-trap).  The recorded fix is
# `#pragma HLS reset variable=x` in the body; BOTH bodies carry those pragmas and Vitis 2025.1
# ignored every one of them -- csynth reported "Register '<x>' is power-on initialization" for all
# 12 state registers (pd_head/pd_tail/pd_count, slot/held/h_*/n_underrun/played_through).
#
# `config_rtl -reset state` at the SOLUTION level takes all 12 to zero, and costs nothing: the
# payload loop still schedules at II=1 and the player still comes out at latency 2.
config_rtl -reset state

csynth_design
exit
"""


def generate(out_dir: Path = HERE) -> None:
    """Emit the schema headers, the two task bodies, the harness top and its tcl."""
    config = BuildConfig(root_dir=out_dir, params={})
    inner = BuildDag()
    inner.add(StreamUtilsStep(output_dir=INCLUDE_DIR))
    inner.add(RfTxStreamStep(output_dir=INCLUDE_DIR))
    for cls in TX_STREAM_SCHEMA_CLASSES:
        inner.add(DataSchemaStep(cls, word_bw_supported=list(WORD_BW_SUPPORTED),
                                 include_dir=INCLUDE_DIR))
    results = inner.run(config, force=True)
    failed = [n for n, r in results.items() if not r.success]
    if failed:
        raise RuntimeError(f"gen-include failed: {failed}")

    gen = out_dir / GEN
    gen.mkdir(parents=True, exist_ok=True)
    (gen / f"{TOP}.cpp").write_text(TOP_CPP, encoding="utf-8")
    (out_dir / f"{TOP}.tcl").write_text(TCL, encoding="utf-8")
    print(f"generated {GEN}/{TOP}.cpp + {TOP}.tcl + {INCLUDE_DIR}/ "
          f"({len(TX_STREAM_SCHEMA_CLASSES)} schemas, 2 task bodies)")


# ---------------------------------------------------------------------------
# The build DAG
# ---------------------------------------------------------------------------


@dataclass(kw_only=True)
class PySimStep(BuildStep):
    """Run the three Stage 1 assertions in SimPy — the toolchain-free checkpoint."""

    description = "Run the rf_repeat_play pysim gate (schedule, TX_TOO_LATE, underrun recovery)."
    consumes = ["rf_repeat_play_source"]
    produces: ClassVar[dict] = {"pysim_results": Path("results/rf_repeat_play_pysim.json")}
    params: ClassVar[dict] = {}

    def run(self, config: BuildConfig, **_) -> dict:
        import json

        from examples.rf_repeat_play.rf_repeat_play import responses, run_pysim

        tb = run_pysim()
        c = dict(tb.dut.counters)
        c["underrun"] = int(tb.dac_if.underrun)
        c["last_underrun_idx"] = int(tb.dac_if.last_underrun_idx)
        c["base"] = int(tb.host.base)
        c["responses"] = responses(tb)
        out = config.root_dir / "results" / "rf_repeat_play_pysim.json"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(c, indent=2), encoding="utf-8")
        return {"pysim_results": out}


@dataclass(kw_only=True)
class GenIncludeStep(BuildStep):
    description = "Emit the schema headers, both task bodies, the csynth harness and its tcl."
    consumes = ["rf_repeat_play_source"]
    produces: ClassVar[dict] = {"top_cpp": Path(f"{GEN}/{TOP}.cpp"), "run_tcl": Path(f"{TOP}.tcl")}
    params: ClassVar[dict] = {}

    def run(self, config: BuildConfig, **_) -> dict:
        generate(config.root_dir)
        return {"top_cpp": config.root_dir / GEN / f"{TOP}.cpp",
                "run_tcl": config.root_dir / f"{TOP}.tcl"}


@dataclass(kw_only=True)
class CSynthStep(BuildStep):
    """Vitis HLS C-synthesis of both task bodies."""

    description = "Run Vitis HLS C-synthesis over the two rf_tx_stream task bodies."
    consumes = ["top_cpp", "run_tcl"]
    produces: ClassVar[dict] = {"report_dir": Path(f"{TOP}_proj/solution1")}
    params: ClassVar[dict] = {"live_output": False}

    def run(self, config: BuildConfig, live_output, **_) -> dict:
        result = toolchain.run_vitis_hls(config.root_dir / f"{TOP}.tcl",
                                         work_dir=config.root_dir,
                                         capture_output=not live_output)
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr)
        return {"report_dir": config.root_dir / f"{TOP}_proj" / "solution1"}


def build_rf_repeat_play_dag() -> BuildDag:
    dag = BuildDag()
    dag.add(SourceStep(artifact="rf_repeat_play_source", path=HERE / "rf_repeat_play.py"))
    dag.add(PySimStep(name="pysim"))
    dag.add(GenIncludeStep(name="gen_include"))
    dag.add(CSynthStep(name="csynth"))
    return dag


if __name__ == "__main__":
    from waveflow.build.cli import run_dag_cli

    run_dag_cli(build_rf_repeat_play_dag,
                description="Build the streaming transmitter: pysim -> gen-include -> csynth.",
                default_through="csynth",
                root_dir=HERE)
