# rf_tx_stream_tasks.tcl — GENERATED by rf_repeat_play_build.py.  Do not edit.
#
# The RF arc's part and clock, so the numbers here are comparable to every other gate in it:
# xczu48dr-ffvg1517-2-e at 4.0 ns.
open_project -reset rf_tx_stream_tasks_proj
set_top rf_tx_stream_tasks
add_files gen/rf_tx_stream_tasks.cpp -cflags "-Iinclude"
open_solution -reset -flow_target vitis solution1
set_part xczu48dr-ffvg1517-2-e
create_clock -period 4.0 -name default

# THE RESET TRAP, CLOSED HERE RATHER THAN IN THE BODIES -- and that placement is measured, not
# assumed.  An hls::task that writes before it reads advances its state registers during reset,
# because a `static x = 0` becomes a simulation initial value in the RTL and its update is emitted
# with no ap_rst term (reference-hls-task-reset-trap).  The recorded fix is
# `#pragma HLS reset variable=x` in the body; BOTH bodies carry those pragmas and Vitis 2025.1
# ignored every one of them -- csynth reported "Register '<x>' is power-on initialization" for all
# 12 state registers (pd_head/pd_tail/pd_count, slot/held/h_*/n_underrun/played_through).
#
# `config_rtl -reset state` at the SOLUTION level takes all 12 to zero, and costs nothing: the
# payload loop still schedules at II=1 and the player still comes out at latency 2.
config_rtl -reset state

csynth_design
exit
