"""Public hardware-schema API exports."""

from .dataschema import (
    BooleanField,
    DataArray,
    DataField,
    DataList,
    DataSchema,
    EnumField,
    FloatField,
    IntField,
    MemAddr,
    ParamSchema,
    VarDataArray,
    Words,
)
from .param import Expr, LazyField, Param, defer_if_symbolic, pmax, pmin
from .dataunion import (
    DataUnion,
    DataUnionHdr,
    LengthField,
    SchemaIDField,
    SchemaRegistry,
    register_schema,
)
from .interface import (
    SobIFMaster,
    SobIFSlave,
    StreamOfBlocksIF,
)
from .memif import (
    AXIMMAddressRange,
    AXIMMCrossBarIF,
    AXIMMProtocol,
    DirectMMIF,
    MMIFMaster,
    MMIFSlave,
    assign_address_ranges,
)
from .memory import (
    AddrUnit,
    Memory,
    MemoryMod,
)
from .regmap import (
    Bit,
    RegAccess,
    RegField,
    RegMap,
    RegMapAccessError,
    RegMapMMIFSlave,
    VitisRegMap,
    VitisRegMapMMIFSlave,
)

__all__ = [
    "DataSchema",
    "DataField",
    "IntField",
    "MemAddr",
    "FloatField",
    "EnumField",
    "BooleanField",
    "DataList",
    "DataArray",
    "VarDataArray",
    "ParamSchema",
    "Param",
    "Expr",
    "LazyField",
    "defer_if_symbolic",
    "pmax",
    "pmin",
    "Words",
    "SchemaRegistry",
    "register_schema",
    "SchemaIDField",
    "LengthField",
    "DataUnionHdr",
    "DataUnion",
    "SobIFMaster",
    "SobIFSlave",
    "StreamOfBlocksIF",
    "AXIMMAddressRange",
    "AXIMMCrossBarIF",
    "AXIMMProtocol",
    "DirectMMIF",
    "MMIFMaster",
    "MMIFSlave",
    "assign_address_ranges",
    "AddrUnit",
    "Memory",
    "MemoryMod",
    "Bit",
    "RegAccess",
    "RegField",
    "RegMap",
    "RegMapAccessError",
    "RegMapMMIFSlave",
    "VitisRegMap",
    "VitisRegMapMMIFSlave",
]
