#!/usr/bin/env python3
"""Turn a file of ordinary decimal numbers into ``data/user_input.txt``.

The on-disk format this package consumes stores floating-point values as **IEEE-754 bit
patterns**, not as decimal text.  That is deliberate -- the whole point of the exercise is 1-ULP
differences, and a "%.17g" round-trip through text can absorb exactly those -- but it is not
something to type by hand.  So write your numbers normally and run this.

Your file has the same shape as the output, with real decimals instead of bit patterns::

    # type float
    # logp 2
    2 3 64
    1.0  2.0  3.0  ...        <- case 0: M*N matrix entries, row-major
    0.5  0.25 ...             <-         then N vector entries
    ...                       <- case 1, and so on

Whitespace and line breaks are free -- only the order matters.  Integer and ``fixed<W,I>`` types
are already stored integers, so for those this only checks and reformats.

    python encode_user_input.py my_numbers.txt
"""
from __future__ import annotations

import re
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "data" / "user_input.txt"


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(f"usage: {Path(sys.argv[0]).name} <your-decimal-file>")
    src = Path(sys.argv[1])
    if not src.exists():
        sys.exit(f"ERROR: {src} does not exist.")

    directives, body = {}, []
    for raw in src.read_text().splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            m = re.match(r"#\s*(type|logp)\s*[:=]?\s*(\S+)", line, re.IGNORECASE)
            if m:
                directives[m.group(1).lower()] = m.group(2)
            continue
        body.extend(line.split())
    for key in ("type", "logp"):
        if key not in directives:
            sys.exit(f"ERROR: {src} is missing a '# {key} ...' line.  Both are required.")
    if len(body) < 3:
        sys.exit(f"ERROR: {src} has no 'n_cases M N' line.")

    n_case, m, n = (int(v) for v in body[:3])
    # Check the kernel's one hard constraint HERE rather than leaving it to make_user_dut.py:
    # this script overwrites data/user_input.txt, so failing a step later would already have
    # replaced whatever was there.
    par = 1 << int(directives["logp"])
    if n % par:
        sys.exit(f"ERROR: N={n} is not a multiple of parEntries={par} (logp={directives['logp']}).\n"
                 f"       xf::blas::gemv asserts N % parEntries == 0.  Pick a logp that divides "
                 f"N,\n       or pad N with zeros.  Nothing was written.")
    if min(n_case, m, n) < 1:
        sys.exit(f"ERROR: n_cases={n_case}, M={m}, N={n} -- all must be >= 1.  Nothing was written.")
    values, want = body[3:], n_case * (m * n + n)
    if len(values) != want:
        sys.exit(f"ERROR: {src} has {len(values)} values after the header; "
                 f"{n_case} cases x (M*N + N) = {n_case} x ({m}*{n} + {n}) = {want} expected.\n"
                 f"       Check n_cases/M/N, or whether a row is short.")

    tname = directives["type"]
    if tname == "float":
        enc = lambda v: struct.unpack("<I", struct.pack("<f", float(v)))[0]
        note = "IEEE-754 32-bit patterns, decimal"
    elif tname == "double":
        enc = lambda v: struct.unpack("<Q", struct.pack("<d", float(v)))[0]
        note = "IEEE-754 64-bit patterns, decimal"
    else:
        # Integers and ap_fixed are already stored integers; reject a decimal point rather than
        # silently truncating it, because a rounding step here is exactly what must not happen.
        def enc(v):
            if re.search(r"[.eE]", v):
                sys.exit(f"ERROR: type {tname} takes STORED INTEGERS, but found {v!r}.\n"
                         f"       For fixed<W,I>, a real value r is stored as round(r * 2**(W-I)).")
            return int(v)
        note = "stored integers"

    encoded = [enc(v) for v in values]
    OUT.parent.mkdir(exist_ok=True)
    lines = [f"# Generated by encode_user_input.py from {src.name}",
             f"# type {tname}", f"# logp {directives['logp']}",
             f"# values are {note}", f"{n_case} {m} {n}"]
    lines += [str(v) for v in encoded]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(HERE)}: {n_case} case(s), M={m}, N={n}, type {tname}")
    print("next:  python make_user_dut.py")


if __name__ == "__main__":
    main()
