#!/usr/bin/env python3
"""Turn ``data/user_input.txt`` into a synthesizable DUT.

The nine shipped DUTs have their sizes baked in at compile time, because that is what synthesis
needs.  Your data will not match them, so this reads the header of your input file and writes
``src/gemv_user_cfg.hpp`` -- the one generated file in this package -- which the ``user`` DUT is
built from.

Run it, then run the flow.  See "Bring your own input" in README.md.

    python make_user_dut.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
INPUT = HERE / "data" / "user_input.txt"
CFG = HERE / "src" / "gemv_user_cfg.hpp"

#: type name -> (C++ type expression, KIND macro, needs W/I)
KINDS = {
    "float": ("float", "WF_KIND_FLOAT", False),
    "double": ("double", "WF_KIND_DOUBLE", False),
    "int8": ("int8_t", "WF_KIND_INT", False),
    "int16": ("int16_t", "WF_KIND_INT", False),
    "int32": ("int32_t", "WF_KIND_INT", False),
    "int64": ("int64_t", "WF_KIND_INT", False),
    "uint16": ("ap_uint<16>", "WF_KIND_UINT", False),
    "uint32": ("ap_uint<32>", "WF_KIND_UINT", False),
}
WIDTHS = {"int8": 8, "int16": 16, "int32": 32, "int64": 64, "uint16": 16, "uint32": 32}


def parse_header(path: Path):
    """Read the directive lines and the ``n_cases M N`` line.  Fail loudly, not silently."""
    if not path.exists():
        sys.exit(f"ERROR: {path} does not exist.  See 'Bring your own input' in README.md.")
    directives, data_line = {}, None
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            m = re.match(r"#\s*(type|logp)\s*[:=]?\s*(\S+)", line, re.IGNORECASE)
            if m:
                directives[m.group(1).lower()] = m.group(2)
            continue
        data_line = line
        break
    if data_line is None:
        sys.exit(f"ERROR: {path} has no data lines -- expected 'n_cases M N' after the comments.")
    for key in ("type", "logp"):
        if key not in directives:
            sys.exit(f"ERROR: {path} is missing a '# {key} ...' directive line.\n"
                     f"       The header must contain '# type <name>' and '# logp <n>'.\n"
                     f"       See 'Bring your own input' in README.md.")
    try:
        n_case, m, n = (int(v) for v in data_line.split()[:3])
    except ValueError:
        sys.exit(f"ERROR: first data line of {path} is {data_line!r}; expected 'n_cases M N'.")
    return directives, n_case, m, n


def main() -> None:
    d, n_case, m, n = parse_header(INPUT)
    tname, logp = d["type"], int(d["logp"])

    fixed = re.fullmatch(r"fixed<(\d+),(\d+)>", tname)
    if fixed:
        w, i = int(fixed.group(1)), int(fixed.group(2))
        ctype, kind = f"ap_fixed<{w}, {i}>", "WF_KIND_FIXED"
    elif tname in KINDS:
        ctype, kind, _ = KINDS[tname]
        w, i = WIDTHS.get(tname, 0), 0
    else:
        sys.exit(f"ERROR: unknown type {tname!r}.\n"
                 f"       Supported: {', '.join(sorted(KINDS))}, or fixed<W,I>.")

    par = 1 << logp
    if n % par:
        sys.exit(f"ERROR: N={n} is not a multiple of parEntries={par} (logp={logp}).\n"
                 f"       The kernel asserts this -- pick a logp that divides N, or pad N.")
    if m < 1 or n < 1 or n_case < 1:
        sys.exit(f"ERROR: n_cases={n_case}, M={m}, N={n} -- all must be >= 1.")

    beats = n // par
    delays = 8 if tname == "double" else (4 if tname == "float" else 1)
    chunks = -(-beats // delays)

    CFG.write_text(f"""// gemv_user_cfg.hpp -- GENERATED by make_user_dut.py from data/user_input.txt.
// Do not edit by hand; re-run the script instead.
//
//   type {tname}   logp {logp} (parEntries {par})   n_cases {n_case}   M {m}   N {n}
//   {beats} beats, Delays={delays}, {chunks} chunk(s)
#ifndef GEMV_USER_CFG_HPP_
#define GEMV_USER_CFG_HPP_

#define WF_KIND_FLOAT  1
#define WF_KIND_DOUBLE 2
#define WF_KIND_INT    3
#define WF_KIND_UINT   4
#define WF_KIND_FIXED  5

#define WF_USER_KIND {kind}
#define WF_USER_M    {m}
#define WF_USER_N    {n}
#define WF_USER_LOGP {logp}
#define WF_USER_W    {w}
#define WF_USER_TYPENAME "{tname}"

typedef {ctype} T_user;

#endif
""")
    print(f"wrote {CFG.relative_to(HERE)}")
    print(f"  type {tname}, M={m}, N={n}, parEntries={par}, {n_case} case(s)")
    print(f"  {beats} beats / Delays={delays} -> {chunks} chunk(s)")
    if delays > 1 and chunks < 4:
        print(f"  NOTE: with fewer than 4 chunks the library's reduction and a plain binary tree\n"
              f"        are the SAME reduction, so this size cannot tell a correct model from one\n"
              f"        with the tree shape wrong.  It still checks the arithmetic; for a\n"
              f"        structural check use N >= {4 * delays * par}.")
    print("\nnext:  vitis-run --mode hls --tcl run.tcl   (with WF_DUTS=user for just this one)")
    print("       python verify.py")


if __name__ == "__main__":
    main()
