"""vecmult_build.py — the VecMult build DAG.

The rungs, in the order the flow teaches them:

    source -> pysim -> codegen_dut -> csim -> csynth -> resources

``pysim`` needs no toolchain and runs in seconds.  ``csim`` replays that exact job through the
hand-written C++ and compares element for element -- the rung that makes "Python golden, C++ twin" a
checked claim rather than an intention, and the reason ``csynth`` consumes its verdict.  ``csynth``
produces every resource counter; ``resources`` attributes the report and files per-module records.

Deliberately **no XSI rung**: this example exists to measure *utilization*, and the counters are
settled at C-synthesis.  Cycle-accuracy is a different question needing a much more expensive gate
--- see ``examples/fir_block`` for a design that does both.

Driven by :func:`~waveflow.build.cli.run_dag_cli`, so ``--list-steps`` / ``--status`` / ``--through``
/ ``--force`` all work without this file implementing any of them::

    python -m examples.vecmult.vecmult_build --list-steps
    python -m examples.vecmult.vecmult_build --through pysim
    python -m examples.vecmult.vecmult_build --through resources --dwid 128 --vlen 4096
"""
from __future__ import annotations

import json
import shutil
import time as _time
from dataclasses import dataclass
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent

from waveflow.build.build import BuildConfig, BuildDag, BuildStep, SourceStep  # noqa: E402
from waveflow.build.cli import run_dag_cli  # noqa: E402
from waveflow.build.composite_gen import (  # noqa: E402
    GEN_DIR,
    composite_top_spec,
    render_tcl,
    render_top,
)
from waveflow.build.elaborate import elaborate  # noqa: E402
from waveflow.build.resource_steps import InspectSynthStep  # noqa: E402
from waveflow.build.streamutils import MemMgrStep, StreamUtilsStep  # noqa: E402
from waveflow.hw.arrayutils import _array_utils_namespace, gen_array_utils  # noqa: E402
from waveflow.hw.dataschema import DataSchemaStep  # noqa: E402
from waveflow.toolchain.toolchain import run_vitis_hls  # noqa: E402

from examples.vecmult.vecmult import (  # noqa: E402
    DEFAULT_DWID,
    DEFAULT_VLEN,
    INCLUDE_DIR,
    SAMP_W,
    Samp,
    VecCmd,
    VecMult,
    VecResp,
    lane_width,
    vec_type,
)

#: Schema classes the gen-include step emits C++ headers for: the command the body reads and the
#: response it writes.
SCHEMA_CLASSES = (VecCmd, VecResp)

TOP = "vec_mult"
PART = "xc7z020clg484-1"
PERIOD_NS = 10

#: Hand-written bodies: copied into ``include/``, never generated over.
HAND_WRITTEN_TASKS = ("vec_mult_task.h",)


def render_types_h() -> str:
    """The one derived header the hand-written body leans on.

    All it does is give the generated array-utils namespace a **stable** alias.  The generated name
    is a function of the element type (``int16_array_utils``), so a body naming it directly would
    break the moment the sample type changed; ``vm_au`` does not.
    """
    au_ns = _array_utils_namespace(Samp)
    return (
        "#ifndef WAVEFLOW_VECMULT_TYPES_H\n"
        "#define WAVEFLOW_VECMULT_TYPES_H\n"
        "// GENERATED by vecmult_build.render_types_h -- do not edit.\n"
        f'#include "{au_ns}.h"\n'
        "\n"
        f"namespace vm_au = {au_ns};\n"
        "\n"
        "#endif  // WAVEFLOW_VECMULT_TYPES_H\n"
    )


def gen_headers(config: BuildConfig, dwid: int = DEFAULT_DWID, vlen: int = DEFAULT_VLEN) -> None:
    """Emit the stream utilities, the memory manager, the payload schema and its array-utils."""
    dag = BuildDag()
    dag.add(StreamUtilsStep(output_dir=INCLUDE_DIR))
    dag.add(MemMgrStep(output_dir=INCLUDE_DIR))
    dag.add(DataSchemaStep(vec_type(vlen), word_bw_supported=[int(dwid)],
                           include_dir=INCLUDE_DIR))
    for cls in SCHEMA_CLASSES:
        dag.add(DataSchemaStep(cls, word_bw_supported=[int(dwid)], include_dir=INCLUDE_DIR))
    results = dag.run(config)
    failed = [n for n, r in results.items() if not r.success]
    if failed:
        raise RuntimeError(f"header generation failed: {failed}")
    gen_array_utils(Samp, [int(dwid)], cfg=config, streamutils_dir=INCLUDE_DIR)


def generate_dut(out_dir: Path = HERE, dwid: int = DEFAULT_DWID,
                 vlen: int = DEFAULT_VLEN) -> Path:
    """Headers, the stable-alias header, the sticky task body, the ``ap_ctrl_none`` top, the TCL."""
    out_dir = Path(out_dir)
    config = BuildConfig(root_dir=out_dir, params={})
    gen_headers(config, dwid=dwid, vlen=vlen)

    inc = out_dir / INCLUDE_DIR
    inc.mkdir(parents=True, exist_ok=True)
    (inc / "vecmult_types.h").write_text(render_types_h(), encoding="utf-8")
    # The testbench needs the same two knobs the top bakes into its task instantiation.  Emitted
    # rather than duplicated, so the TB cannot drift from the DUT it is checking.
    # The vector directory travels in the header too, as an absolute path with forward slashes.
    # Passing it as a -D through TCL does not survive the quoting on Windows, and csim runs from
    # <proj>/<solution>/csim/build, so a relative path would depend on that depth.
    data_dir = (out_dir / "data").resolve().as_posix()
    (inc / "vec_mult_params.h").write_text(
        "#ifndef WAVEFLOW_VEC_MULT_PARAMS_H\n"
        "#define WAVEFLOW_VEC_MULT_PARAMS_H\n"
        "// GENERATED by vecmult_build.generate_dut -- do not edit.\n"
        f"#define VM_DWID {int(dwid)}\n"
        f"#define VM_VLEN {int(vlen)}\n"
        f'#define VM_DATA_DIR "{data_dir}"\n'
        "#endif\n", encoding="utf-8")

    for name in HAND_WRITTEN_TASKS:
        src = out_dir / name
        if not src.exists():
            raise FileNotFoundError(f"hand-written task body missing: {src}")
        shutil.copyfile(src, inc / name)

    comp = elaborate(VecMult, {"dwid": int(dwid), "vlen": int(vlen)}, name=TOP)
    spec = composite_top_spec(comp, width=int(dwid))
    gen = out_dir / GEN_DIR
    gen.mkdir(parents=True, exist_ok=True)
    cpp = gen / f"{spec.top_name}.cpp"
    cpp.write_text(render_top(spec), encoding="utf-8")
    (out_dir / f"{spec.top_name}.tcl").write_text(
        render_tcl(spec.top_name, part=PART, period_ns=PERIOD_NS), encoding="utf-8")
    print(f"generated {cpp.relative_to(out_dir)} + {spec.top_name}.tcl "
          f"(dwid={dwid}, vlen={vlen}, LW={lane_width(dwid)})")
    return cpp


# ---------------------------------------------------------------------------
# The build DAG
# ---------------------------------------------------------------------------


@dataclass(kw_only=True)
class PySimStep(BuildStep):
    """Run one firing in SimPy and check the output against :func:`golden`.

    The first checkpoint: no toolchain, and it catches any packing error in the lane serialization
    before five minutes of Vitis would.  Raises on mismatch, so "it ran" is never mistaken for
    "it is correct".
    """

    description = "Run the VecMult pysim golden (one vector through, checked element-wise)."
    consumes = ["vecmult_source"]
    produces = {"pysim_results": Path("results/pysim.json"),
                "csim_vectors": Path("data/meta.txt")}
    params = {"dwid": DEFAULT_DWID, "vlen": DEFAULT_VLEN}

    def run(self, config: BuildConfig, dwid, vlen, **_) -> dict:
        from examples.vecmult.vecmult_sim import run_one, write_vectors

        dwid, vlen = int(dwid), int(vlen)
        tx_id = 0x5A5A
        # A ragged length, deliberately: n < vlen and not a multiple of LW exercises the partial
        # final beat, which is where a lane-serialized body breaks and a full-length run never looks.
        n = max(1, vlen - 3)
        got, exp, echoed = run_one(dwid=dwid, vlen=vlen, n=n, seed=0, tx_id=tx_id)
        bad = int(np.count_nonzero(np.asarray(got) != np.asarray(exp)))
        if bad:
            first = int(np.argmax(np.asarray(got) != np.asarray(exp)))
            raise RuntimeError(
                f"pysim mismatch in {bad}/{n} samples; first at index {first}: "
                f"got {got[first]}, expected {exp[first]}")
        if echoed != tx_id:
            raise RuntimeError(f"response tx_id {echoed} != command tx_id {tx_id}")
        out = config.root_dir / "results" / "pysim.json"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps({"dwid": dwid, "vlen": vlen, "n": n, "lw": lane_width(dwid),
                                   "samp_w": SAMP_W, "samples_checked": int(n),
                                   "tx_id_echoed": int(echoed)},
                                  indent=2), encoding="utf-8")
        # The same stimulus and expectation the C++ testbench replays.  Written here rather than by
        # the csim rung so there is exactly one definition of the job under test.
        write_vectors(config.root_dir / "data", dwid=dwid, vlen=vlen, n=n, seed=0, tx_id=tx_id)
        print(f"  pysim OK — n={n} of vlen={vlen}, LW={lane_width(dwid)}, tx_id echoed")
        return {"pysim_results": out, "csim_vectors": config.root_dir / "data" / "meta.txt"}


@dataclass(kw_only=True)
class CodegenDutStep(BuildStep):
    """Lower ``VecMult`` to its ``ap_ctrl_none`` top, plus the headers the body includes."""

    description = "Lower VecMult to the ap_ctrl_none top (+ tcl, headers, array-utils)."
    consumes = ["vecmult_source"]
    produces = {"vec_mult_cpp": Path("gen/vec_mult.cpp"), "run_tcl": Path("vec_mult.tcl")}
    params = {"dwid": DEFAULT_DWID, "vlen": DEFAULT_VLEN}

    def run(self, config: BuildConfig, dwid, vlen, **_) -> dict:
        generate_dut(config.root_dir, dwid=int(dwid), vlen=int(vlen))
        return {"vec_mult_cpp": config.root_dir / GEN_DIR / f"{TOP}.cpp",
                "run_tcl": config.root_dir / f"{TOP}.tcl"}


@dataclass(kw_only=True)
class CsimStep(BuildStep):
    """Replay the pysim job through the hand-written C++ and compare, element for element.

    The rung that makes "Python golden, C++ twin" a checked claim rather than an intention.  pysim
    proves the Python body; csynth proves the C++ compiles and schedules.  Only this proves they
    agree — and it costs seconds, against the minutes a synthesis costs.
    """

    description = "Vitis C-simulation of the task body against the pysim vectors."
    consumes = ["vec_mult_cpp", "csim_vectors"]
    produces = {"csim_verdict": Path("results/csim_verdict.json")}
    params = {"live_output": False}

    def run(self, config: BuildConfig, live_output=False, **_) -> dict:
        result = run_vitis_hls(config.root_dir / f"{TOP}_csim.tcl", work_dir=config.root_dir,
                               capture_output=not live_output)
        out_txt = (result.stdout or "") + (result.stderr or "")
        if "WAVEFLOW_CSIM_OK" not in out_txt or "WAVEFLOW_CSIM_FAIL" in out_txt:
            print(out_txt[-4000:])
            raise RuntimeError("csim did not report WAVEFLOW_CSIM_OK — the C++ and the Python "
                               "golden disagree, or the run failed")
        verdict = config.root_dir / "results" / "csim_verdict.json"
        verdict.parent.mkdir(parents=True, exist_ok=True)
        line = next((ln.strip() for ln in out_txt.splitlines() if "WAVEFLOW_CSIM_OK" in ln), "")
        verdict.write_text(json.dumps({"ok": True, "report": line}, indent=2), encoding="utf-8")
        print(f"  csim OK — {line}")
        return {"csim_verdict": verdict}


@dataclass(kw_only=True)
class CSynthStep(BuildStep):
    """Vitis HLS C-synthesis — where every resource counter on this example comes from.

    Publishes ``synth_seconds`` as an artifact rather than only printing it: a resource record's
    ``cost_seconds`` is what later makes "K syntheses sufficed for N design points" auditable, and
    it is unrecoverable if not captured when spent.
    """

    description = "Run Vitis HLS C-synthesis of the generated top."
    consumes = ["vec_mult_cpp", "run_tcl", "csim_verdict"]
    produces = {"report_dir": Path(f"{TOP}_proj/solution1"), "synth_seconds": None}
    params = {"live_output": False}

    def run(self, config: BuildConfig, live_output=False, **_) -> dict:
        started = _time.perf_counter()
        result = run_vitis_hls(config.root_dir / f"{TOP}.tcl", work_dir=config.root_dir,
                               capture_output=not live_output)
        elapsed = _time.perf_counter() - started
        out = (result.stdout or "") + (result.stderr or "")
        if "WAVEFLOW_CSYNTH_OK" not in out:
            print(out[-4000:])
            raise RuntimeError("csynth did not report WAVEFLOW_CSYNTH_OK")
        print(f"  csynth took {elapsed:.1f}s")
        return {"report_dir": config.root_dir / f"{TOP}_proj" / "solution1",
                "synth_seconds": elapsed}


def build_vecmult_dag() -> BuildDag:
    dag = BuildDag()
    dag.add(SourceStep(artifact="vecmult_source", path=HERE / "vecmult.py"))
    dag.add(PySimStep(name="pysim"))
    dag.add(CodegenDutStep(name="codegen_dut"))
    dag.add(CsimStep(name="csim"))
    dag.add(CSynthStep(name="csynth"))
    dag.add(InspectSynthStep(
        name="resources", comp_class=VecMult, top_name=TOP,
        elaborate_params=("dwid", "vlen"),
        params={"dwid": DEFAULT_DWID, "vlen": DEFAULT_VLEN}))
    return dag


def main() -> None:
    run_dag_cli(
        build_vecmult_dag,
        description="Build and check the vecmult example.",
        default_through="pysim",
        root_dir=HERE,
        extra_args=[
            (("--dwid",), {"type": int, "default": DEFAULT_DWID,
                           "help": f"Stream word width in bits (default {DEFAULT_DWID})."}),
            (("--vlen",), {"type": int, "default": DEFAULT_VLEN,
                           "help": f"Samples per vector (default {DEFAULT_VLEN})."}),
            (("--live-output",), {"action": "store_true",
                                  "help": "Stream Vitis output live (csynth)."}),
        ],
        params_from_args=lambda a: {"dwid": a.dwid, "vlen": a.vlen,
                                    "live_output": a.live_output},
    )


if __name__ == "__main__":
    main()
