// gemv_user_cfg.hpp -- GENERATED by make_user_dut.py from data/user_input.txt.
// Do not edit by hand; re-run the script instead.
//
//   type float   logp 2 (parEntries 4)   n_cases 2   M 3   N 64
//   16 beats, Delays=4, 4 chunk(s)
#ifndef GEMV_USER_CFG_HPP_
#define GEMV_USER_CFG_HPP_

#define WF_KIND_FLOAT  1
#define WF_KIND_DOUBLE 2
#define WF_KIND_INT    3
#define WF_KIND_UINT   4
#define WF_KIND_FIXED  5

#define WF_USER_KIND WF_KIND_FLOAT
#define WF_USER_M    3
#define WF_USER_N    64
#define WF_USER_LOGP 2
#define WF_USER_W    0
#define WF_USER_TYPENAME "float"

typedef float T_user;

#endif
