#!/usr/bin/env python3
"""Generate data/input.txt for the 1024-point test.

At L=16 the inputs are small enough to read; at 1024 they are not, so they are generated from
a fixed formula instead -- deterministic, and the file is checked in so a run needs no
regeneration.  The vector *kinds* mirror the 16-point test, including the boundary cases that
matter (see ../verifyFFT16/README.md for why those are there).

Fewer vectors than the 16-point test: co-simulating 1024 points is far slower, and the extra
in-range vectors add little once the boundary ones are covered.
"""
from pathlib import Path

W = 16                       # must match FFT_IN_W in src/fft_top.hpp
L = 1024
MASK = (1 << W) - 1
MOST_NEG, MOST_POS = 1 << (W - 1), (1 << (W - 1)) - 1

KINDS = [
    ("ramp", lambda n: ((n * 2731 + 17) & MASK, (n * 5417 + 913) & MASK)),
    ("pseudo-random", lambda n: (((n * 40503 + 20759) * 2654435761) & MASK,
                                 ((n * 15485 + 7919) * 40503) & MASK)),
    ("impulse", lambda n: ((1 << (W - 2)) if n == 0 else 0,
                           (-(1 << (W - 2)) & MASK) if n == 3 else 0)),
    ("constant", lambda n: (12345, (1 << W) - 9876)),
    ("alternating-extremes", lambda n: ((MOST_POS if n % 2 else MOST_NEG),
                                        (MOST_NEG if n % 2 else MOST_POS))),
    ("all-most-negative", lambda n: (MOST_NEG, MOST_NEG)),
    ("all-most-positive", lambda n: (MOST_POS, MOST_POS)),
    ("mixed-extremes", lambda n: ((MOST_NEG if n % 4 == 0 else (n * 8191) & MASK),
                                  (MOST_POS if n % 4 == 1 else (n * 4093) & MASK))),
]


def main() -> None:
    out = Path(__file__).resolve().parent / "data" / "input.txt"
    out.parent.mkdir(exist_ok=True)
    lines = [f"# Vitis SSR FFT verification input (L={L})",
             f"# raw STORED integers of ap_fixed<{W},2>, unsigned two's-complement",
             "# generated by gen_input.py -- vector kinds mirror the 16-point test",
             "# " + ", ".join(f"v{i}={k}" for i, (k, _) in enumerate(KINDS)),
             "# format:  <n_vectors> <n_samples>   then one 're im' pair per line, vector-major",
             f"{len(KINDS)} {L}"]
    for _, fn in KINDS:
        for n in range(L):
            re, im = fn(n)
            lines.append(f"{re & MASK} {im & MASK}")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(KINDS)} vectors x {L} samples")


if __name__ == "__main__":
    main()
