#!/usr/bin/env python3
"""Write the build tree for the S2/S3 check, using the framework pieces it exercises.

Nothing here is hand-maintained C++ beyond ``src/tb.cpp``: the body header is produced by
:class:`~waveflow.build.vitis_l1_step.VitisL1Step` (a copy step), the vendor include path by
:func:`~waveflow.build.vitis_l1_step.vitis_fft_include_dir`, and the TCL by
:func:`~waveflow.build.composite_gen.render_tcl` — so if any of those break, this stops working.

    python build.py && vitis-run --mode hls --tcl run.tcl && python verify.py
"""
from __future__ import annotations

from pathlib import Path

from waveflow.build.composite_gen import render_tcl
from waveflow.build.vitis_l1_step import VitisL1Step, vitis_fft_include_dir

HERE = Path(__file__).resolve().parent
TOP = "vitis_fft_top"
#: Must match data/input.txt and the golden. L=16 keeps co-simulation to under a minute.
L, R, IN_W, IN_I, TW_W, TW_I, SCALING, ORDER, OUT_W = 16, 4, 16, 2, 18, 2, 0, 0, 21


def main() -> None:
    (HERE / "include").mkdir(exist_ok=True)
    (HERE / "gen").mkdir(exist_ok=True)

    (HERE / "include" / "vitis_fft_task.h").write_text(
        VitisL1Step(output_dir="include").generate("vitis_fft_task", None), encoding="utf-8")

    # A stand-in for what the composite generator will emit once VitisFft is wired through it:
    # the same call, with the same template arguments VitisFft.kernel_task() reports.
    ins = ",\n                   ".join(f"hls::stream<ap_uint<{2*IN_W}> >& s_in_{i}"
                                        for i in range(R))
    outs = ",\n                   ".join(f"hls::stream<ap_uint<{2*OUT_W}> >& m_out_{i}"
                                         for i in range(R))
    args = ", ".join([f"s_in_{i}" for i in range(R)] + [f"m_out_{i}" for i in range(R)])
    (HERE / "gen" / f"{TOP}.cpp").write_text(f'''\
// Generated by build.py -- the call the composite generator will emit for VitisFft.
#include "vitis_fft_task.h"

void {TOP}({ins},
                   {outs}) {{
#pragma HLS TOP
    vitis_fft_impl::vitis_fft_task<{L}, {IN_W}, {IN_I}, {TW_W}, {TW_I}, {SCALING}, {ORDER}, \
{OUT_W}>({args});
}}
''', encoding="utf-8")

    vlib = vitis_fft_include_dir()
    # csim and cosim run from inside the project tree, so -argv paths must be ABSOLUTE.  A
    # relative one opens nothing, and the testbench then dereferences a NULL FILE* -- which
    # presents as "CSim failed with errors / SIGSEGV" and names neither cause.
    inp, csim_out, cosim_out = (HERE / "data" / "input.txt", HERE / "results" / "output_csim.txt",
                                HERE / "results" / "output_cosim.txt")
    tcl = render_tcl(TOP, include_dirs=(str(vlib),)).splitlines()
    tcl = [ln for ln in tcl if not ln.startswith(("if {[catch {csynth", "puts \"WAVEFLOW_CSYNTH",
                                                  "exit 0"))]
    tcl += [
        f'add_files -tb {HERE / "src" / "tb.cpp"} -cflags $cf',
        f'if {{[catch {{csim_design -argv "{inp} {csim_out}"}} r]}} '
        f'{{ puts "WAVEFLOW_ERROR: csim"; puts $r; exit 1 }}',
        'puts "WAVEFLOW_CSIM_OK"',
        'if {[catch {csynth_design} r]} { puts "WAVEFLOW_ERROR: csynth"; puts $r; exit 1 }',
        'puts "WAVEFLOW_CSYNTH_OK"',
        f'if {{[catch {{cosim_design -argv "{inp} {cosim_out}" -trace_level none}} r]}} '
        f'{{ puts "WAVEFLOW_ERROR: cosim"; puts $r; exit 1 }}',
        'puts "WAVEFLOW_COSIM_OK"',
        'exit 0',
    ]
    (HERE / "run.tcl").write_text("\n".join(tcl) + "\n", encoding="utf-8")
    print(f"wrote include/, gen/{TOP}.cpp and run.tcl   (vendor -I = {vlib})")
    print("next:  vitis-run --mode hls --tcl run.tcl   &&   python verify.py")


if __name__ == "__main__":
    main()
