"""``StreamDriver``'s inter-burst gaps -- the pysim half of the AxisMaster ``burst_gap*`` pair.

A pipelined block has to be checked with frames that do NOT arrive back to back: a frame that only
leaves when the next one pushes it is invisible otherwise, and a block whose latency depends on
arrival phase can only be calibrated with arrivals spread over that phase.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from waveflow.hw.clock import Clock
from waveflow.hw.interface import StreamIF
from waveflow.simulation.simulation import Simulation
from waveflow.simulation.stream_tb import StreamDriver, StreamSink
from waveflow.utils.burst_io import write_burst_bundle


@dataclass
class _StampSink(StreamSink):
    def __post_init__(self) -> None:
        super().__post_init__()
        self.stamps: list[float] = []

    def rx_proc(self, words):
        self.stamps.append(self.now)
        yield from super().rx_proc(words)


def _run(tmp_path, **gaps) -> list[float]:
    write_burst_bundle([np.arange(4, dtype=np.uint64)] * 4, tmp_path / "v")
    sim, clk = Simulation(), Clock(freq=100e6)
    drv = StreamDriver(name="d", sim=sim, bitwidth=32, in_bundle="v", root=tmp_path, **gaps)
    snk = _StampSink(name="s", sim=sim, bitwidth=32)
    ch = StreamIF(name="c", sim=sim, clk=clk, bitwidth=32)
    ch.bind("master", drv.stream_ep)
    ch.bind("slave", snk.stream_ep)
    sim.run_sim()
    return [round(t / clk.period) for t in snk.stamps]


def test_gap_rule_list_then_scalar():
    d = StreamDriver(name="d", sim=Simulation(), burst_gap_cycles=5, burst_gaps=[10, 20])
    assert [d.gap_before(k) for k in range(5)] == [0, 10, 20, 5, 5]


def test_bursts_are_spaced_by_their_gaps(tmp_path):
    assert _run(tmp_path) == [4, 8, 12, 16]                       # back to back
    assert _run(tmp_path, burst_gap_cycles=3) == [4, 11, 18, 25]  # +3 idle before each
    assert _run(tmp_path, burst_gaps=[10, 0, 1]) == [4, 18, 22, 27]


def test_defaults_emit_nothing():
    """Unset gaps are falsy DynParams, so an existing harness is generated byte-for-byte as before."""
    from waveflow.hw.hw_module import discover_dyn_params
    dyn = discover_dyn_params(StreamDriver(name="d", sim=Simulation(), in_bundle="v"))
    assert "burst_gap_cycles" not in dyn and "burst_gaps" not in dyn
