#ifndef WAVEFLOW_FIR_COMPUTE_TASK_H
#define WAVEFLOW_FIR_COMPUTE_TASK_H
// fir_compute_task.h — the block FIR's stateful compute: the CUSTOM kernel, and the whole reason
// examples/fir_block exists.  Reads the framed [FirDesc | data] off the reader and frames the writer's
// stream [MemWCmd | FirDesc | y].  One body, two opcodes:
//
//   LOAD_TAPS — the n words are coefficients.  They land in `taps` and stay there, across every later
//               firing.  Nothing is written back.
//   FILTER    — the n words are a block.  y[i] = sum_k taps[k] * x[i-k], where the k > i terms come
//               from `carry` (the previous block's tail) unless zero_state selects zeros.  The new
//               tail is written back to `carry` for the next firing.
//
// THE STORAGE IS NOT DECLARED HERE.  `fir_compute_state.inc` is generated by
// build/hwgen.py::state_decls_to_cpp from FirCompute's add_state registrations, so the element type,
// the extents, and the ARRAY_PARTITION pragma are single-sourced from the same Python objects the
// pysim twin mutates.  The arithmetic below is hand-written; the state it runs on is not, which is
// what stops the RTL's `static` and the model's HwState from silently drifting apart.
//
// Two things that are load-bearing and easy to get wrong:
//
//  1. THE NO-OUTPUT OPCODE STILL COMPLETES.  LOAD_TAPS frames MemWCmd{len=0, fwd_bursts=1}, so the
//     writer's store loop trips zero times (no AXI transaction at all) while its echo loop still emits
//     the descriptor on s_done.  A stage that consumes input and emits nothing is exactly the shape
//     that has deadlocked this codebase twice (the free-run pacing law; the mem_r_stream phantom
//     read), so the write side is kept UNIFORM across both opcodes rather than branching around it.
//  2. THE ACCUMULATOR IS DERIVED, NOT HAND-SIZED.  acc_t comes from fir_compute_types.h, which runs
//     the same format algebra as the model: ap_fixed multiply gives <2W, 2I> and the T-tap sum grows
//     the integer bits by ceil(log2 T).  acc_t has exactly the product's fractional bits, so the
//     running sum is EXACT and the only lossy step is the final assignment to samp_t (AP_TRN/AP_WRAP)
//     — the declared quantize.  Writing `2*W + 5` here by hand is how that becomes almost-bit-exact.
//
// Transport is one sample per MEM_DW word, in the low SAMP_W bits (see fir_block.py).  Single-firing;
// touches only streams.  Its pysim twin is FirCompute.run_iter (examples/fir_block/fir_block.py).
#include "hls_stream.h"
#include <ap_int.h>
#include <ap_fixed.h>
#include "streamutils_hls.h"
#include "fir_op.h"
#include "fir_desc.h"
#include "mem_w_cmd.h"
#include "fir_compute_types.h"

template <int MEM_DW>
static void fir_compute_task(hls::stream<streamutils::framed_word<MEM_DW> >& s_in,
                             hls::stream<streamutils::framed_word<MEM_DW> >& cmd_out) {
    typedef streamutils::framed_word<MEM_DW> word_t;
    typedef fir_compute_types::samp_t samp_t;
    typedef fir_compute_types::acc_t acc_t;
    const int NTAP = fir_compute_types::NTAP;
    const int SAMP_W = fir_compute_types::SAMP_W;

// Cross-firing state, emitted from FirCompute.add_state -- see the header comment.  Included INSIDE
// the body because that is the site declared state lands at for a free-running hls::task: a task has
// no "before the loop", so this declaration IS the initialization site, and `static` here is what
// survives the runtime re-firing the body per command.
#include "fir_compute_state.inc"

    FirDesc d;
    streamutils::tlast_status tl;
    d.read_framed_stream<MEM_DW>(s_in, tl);
    const int n = (int)d.n;
    bool last;

    if (d.op == FirOp::LOAD_TAPS) {
        // Latch the coefficients.  This is the "load once, held" flavour: nothing else in the firing
        // touches memory, and every FILTER after it reads what landed here.
    LOAD: for (int k = 0; k < n; ++k) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT max=NTAP
            ap_uint<MEM_DW> w = streamutils::read_boundary_word<word_t, MEM_DW>(s_in, last);
            taps[k] = streamutils::bits_to_fixed<samp_t>((ap_uint<SAMP_W>)w.range(SAMP_W - 1, 0));
        }
        // len=0: no data follows, no AXI write happens -- but fwd_bursts=1 still carries the
        // descriptor through to s_done, so this job completes like any other.
        MemWCmd memw;
        memw.addr = d.dst_off;
        memw.len = 0;
        memw.fwd_bursts = 1;
        memw.write_framed_stream<MEM_DW>(cmd_out);
        d.write_framed_stream<MEM_DW>(cmd_out);
    } else {
        // Frame the writer FIRST, so it is already draining while the FIR streams samples at it.
        MemWCmd memw;
        memw.addr = d.dst_off;
        memw.len = n;
        memw.fwd_bursts = 1;
        memw.write_framed_stream<MEM_DW>(cmd_out);
        d.write_framed_stream<MEM_DW>(cmd_out);

        // The delay line.  During the MAC of iteration i, dline[k] == x[i-k]; but each iteration
        // SHIFTS BEFORE it accumulates, so what has to be seeded is the state at the TOP of iteration
        // 0, where dline[j] == x[-1-j].  In carry terms (carry is the previous block's tail, stored
        // oldest-first) that is dline[j] = carry[NTAP-2-j].
        //
        // Seeding `dline[k] = carry[NTAP-1-k]` instead -- i.e. writing down the MAC-time invariant --
        // is the natural-looking spelling and it is WRONG: the first SHIFT slides it one slot, which
        // drops the newest carry sample and pushes dline[0]'s dummy zero into dline[1].  The damage
        // is invisible in block 1 (zero_state starts from zeros anyway) and invisible to csynth; it
        // shows up only as block 2's first samples, which is exactly what XSI caught.
        //
        // zero_state selects zeros instead: the design's DECLARED reset path, as opposed to whatever
        // ap_rst happens to do to a static.
        samp_t dline[NTAP];
#pragma HLS ARRAY_PARTITION variable=dline complete dim=1
    SEED: for (int j = 0; j < NTAP - 1; ++j) {
#pragma HLS UNROLL
            dline[j] = (d.zero_state != 0) ? (samp_t)0 : carry[NTAP - 2 - j];
        }
        dline[NTAP - 1] = (samp_t)0;   // overwritten by the first SHIFT before any MAC reads it

    FIR: for (int i = 0; i < n; ++i) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT max=4096
            ap_uint<MEM_DW> w = streamutils::read_boundary_word<word_t, MEM_DW>(s_in, last);
            samp_t x = streamutils::bits_to_fixed<samp_t>((ap_uint<SAMP_W>)w.range(SAMP_W - 1, 0));
        SHIFT: for (int k = NTAP - 1; k > 0; --k) {
#pragma HLS UNROLL
                dline[k] = dline[k - 1];
            }
            dline[0] = x;
            // Full-precision MAC: every product enters acc_t exactly (same fractional bits), so the
            // sum cannot round or overflow.  The single lossy step is the assignment to samp_t below.
            acc_t acc = 0;
        MAC: for (int k = 0; k < NTAP; ++k) {
#pragma HLS UNROLL
                acc += (acc_t)(taps[k] * dline[k]);
            }
            samp_t y = (samp_t)acc;                 // the declared quantize (AP_TRN / AP_WRAP)
            ap_uint<MEM_DW> ow = 0;                 // one sample per word, low SAMP_W bits
            ow.range(SAMP_W - 1, 0) = streamutils::fixed_to_bits<samp_t>(y);
            streamutils::write_boundary_word<word_t, MEM_DW>(cmd_out, ow, (i + 1 == n));
        }

        // Hand the tail to the next firing.  After the last iteration dline[k] == x[n-1-k], so the
        // last NTAP-1 samples stored oldest-first are carry[j] = dline[NTAP-2-j] -- exactly the
        // ordering SEED reads back.  Taking it off the delay line rather than capturing the words as
        // they stream past also keeps a block SHORTER than the carry correct for free: the shift
        // register still holds the older samples, so the boundary spans blocks the way it should.
    SAVE: for (int j = 0; j < NTAP - 1; ++j) {
#pragma HLS UNROLL
            carry[j] = dline[NTAP - 2 - j];
        }
    }
}

#endif  // WAVEFLOW_FIR_COMPUTE_TASK_H
