// fir_block_bfm_tb.cpp -- GENERATED by waveflow (build/composite_gen.py::render_tb_main)
// from the fir_block testbench graph.  DO NOT EDIT: regenerate instead.
//
// The whole TB main: construct the generated harness, run a fixed number of cycles (the
// participants load their input bundles in pre_sim and dump their outputs in post_sim), then
// close.  No golden here -- correctness is checked in Python from the dumped output bundles.
#include "fir_block_tb_harness.h"

int main() {
    fir_block_tb::Harness h("fir_block_bfm.wdb");
    h.run(8000);
    h.close();
    return 0;
}
