#ifndef WAVEFLOW_GEN_FIR_BLOCK_VECTORS_H
#define WAVEFLOW_GEN_FIR_BLOCK_VECTORS_H
// fir_block_vectors.h -- GENERATED by waveflow (build/composite_gen.py::render_vectors_h).
// DO NOT EDIT: regenerate instead.  Plain C++ (no HLS types) so a host-compiled testbench
// can include it.  Command words are the output of the schema's own serialize() -- the
// testbench never re-implements a packing rule, so it cannot drift from the schema.
// Derived from the FirBlockTB graph (examples/fir_block/fir_block_sim.py) -- the same
// class the pysim golden runs.  The command words, the taps/input arena, and the golden
// ride the burst bundles under xsi/vectors/, written by write_xsi_bundles.
#include <cstdint>

namespace fir_block_vectors {

static const int MEM_DW = 32;
static const int MEM_NW = 240;
static const int NUM_CMDS = 5;
static const int DONE_WORDS = 5;

}  // namespace fir_block_vectors

#endif  // WAVEFLOW_GEN_FIR_BLOCK_VECTORS_H
