#ifndef WAVEFLOW_GEN_FIR_BLOCK_PORTS_H
#define WAVEFLOW_GEN_FIR_BLOCK_PORTS_H
// fir_block_ports.h -- GENERATED by waveflow (build/composite_gen.py::render_ports_h) from the SAME
// TopSpec that emits fir_block's interface pragmas.  DO NOT EDIT: regenerate instead.
// One spec, two consumers -- so a testbench cannot drift from the kernel it drives.

namespace fir_block_ports {

static const char* const TOP        = "fir_block";
static const char* const DESIGN_DLL = "xsim.dir/fir_block/xsimk.dll";

static const char* const s_cmd    = "s_cmd";   // axis_in
static const char* const m_in     = "m_axi_gmem0";   // maxi_read on gmem0
static const char* const m_out    = "m_axi_gmem1";   // maxi_write on gmem1
static const char* const s_done   = "s_done";   // axis_out

// Every TB-driven input the interface models above do not themselves drive.  Absent names
// are skipped at bind time (XsiSim::pin_low), so this may name channels a given kernel
// does not expose.
static const char* const ZERO_PORTS[] = {
    "s_axi_control_AWVALID",
    "s_axi_control_AWADDR",
    "s_axi_control_WVALID",
    "s_axi_control_WDATA",
    "s_axi_control_WSTRB",
    "s_axi_control_ARVALID",
    "s_axi_control_ARADDR",
    "s_axi_control_RREADY",
    "s_axi_control_BREADY",
    "m_axi_gmem0_AWREADY",
    "m_axi_gmem0_WREADY",
    "m_axi_gmem0_BVALID",
    "m_axi_gmem0_BRESP",
    "m_axi_gmem0_BID",
    "m_axi_gmem0_BUSER",
    "m_axi_gmem0_RRESP",
    "m_axi_gmem0_RID",
    "m_axi_gmem0_RUSER",
    "m_axi_gmem1_ARREADY",
    "m_axi_gmem1_RVALID",
    "m_axi_gmem1_RDATA",
    "m_axi_gmem1_RLAST",
    "m_axi_gmem1_RRESP",
    "m_axi_gmem1_RID",
    "m_axi_gmem1_RUSER",
    "m_axi_gmem1_BRESP",
    "m_axi_gmem1_BID",
    "m_axi_gmem1_BUSER",
};
static const int ZERO_PORTS_N = (int)(sizeof(ZERO_PORTS)/sizeof(ZERO_PORTS[0]));

}  // namespace fir_block_ports

#endif  // WAVEFLOW_GEN_FIR_BLOCK_PORTS_H
