#!/usr/bin/env python3
"""Turn complex samples written as ordinary decimals into an FFT input file.

The input format this package consumes stores each sample as its **raw stored integer** -- the
``ap_fixed`` bit field, not a decimal.  That is deliberate: bit-exactness is a claim about stored
bits, and a decimal round-trip can absorb exactly the 1-LSB differences the whole exercise exists
to detect.  But it is not something to work out by hand, so write your samples normally and run
this.

    a real value  r  in ap_fixed<W,I>  is stored as  round(r * 2**(W-I))

with ``W`` and ``I`` taken from ``src/fft_top.hpp``, so this always matches the DUT you are about
to build.  Values outside the format's range are refused rather than silently wrapped.

Your file is one complex sample per line, ``re im``, vectors back to back::

    # 2 vectors of 16 samples          <- comments are ignored
    0.5    0.0
    0.25  -0.125
    ...

    python encode_input.py my_samples.txt            # -> data/user_input.txt
    python encode_input.py my_samples.txt --vectors 2

See "Bring your own input" in README.md.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent


def dut_format() -> tuple[int, int, int]:
    """``(W, I, L)`` from the DUT header -- the same source ``verify.py`` reads."""
    text = (HERE / "src" / "fft_top.hpp").read_text()
    vals = {}
    for key in ("FFT_IN_W", "FFT_IN_I", "FFT_L"):
        m = re.search(rf"^\s*#define\s+{key}\s+(\d+)", text, re.MULTILINE)
        if not m:
            sys.exit(f"ERROR: no '#define {key}' in src/fft_top.hpp")
        vals[key] = int(m.group(1))
    return vals["FFT_IN_W"], vals["FFT_IN_I"], vals["FFT_L"]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source", help="text file of 're im' decimal pairs, one sample per line")
    ap.add_argument("--vectors", type=int, default=None,
                    help="number of vectors (default: inferred from the sample count and L)")
    ap.add_argument("-o", "--out", default="data/user_input.txt", help="output path")
    args = ap.parse_args()

    src = Path(args.source)
    if not src.exists():
        sys.exit(f"ERROR: {src} does not exist.")
    w, i, length = dut_format()
    frac = w - i
    lo, hi = -(1 << (w - 1)), (1 << (w - 1)) - 1
    lo_r, hi_r = lo / 2.0 ** frac, hi / 2.0 ** frac

    pairs = []
    for lineno, raw in enumerate(src.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 2:
            sys.exit(f"ERROR: {src}:{lineno}: expected 're im', got {len(parts)} field(s): {line!r}")
        try:
            pairs.append((float(parts[0]), float(parts[1])))
        except ValueError:
            sys.exit(f"ERROR: {src}:{lineno}: not a number: {line!r}")

    if not pairs:
        sys.exit(f"ERROR: {src} contains no samples.")
    if len(pairs) % length:
        sys.exit(f"ERROR: {src} has {len(pairs)} samples, which is not a multiple of the DUT's "
                 f"L={length}.\n       Either pad to a multiple of {length}, or change FFT_L in "
                 f"src/fft_top.hpp (and rebuild).")
    n_vec = args.vectors if args.vectors is not None else len(pairs) // length
    if n_vec * length != len(pairs):
        sys.exit(f"ERROR: --vectors {n_vec} x L={length} = {n_vec * length}, but {src} has "
                 f"{len(pairs)} samples.")

    def store(v: float, lineno_hint: int) -> int:
        # Refuse rather than wrap: a value the format cannot hold is a mistake in the data, and
        # silently folding it would make the comparison meaningless in a way nobody would notice.
        if not (lo_r <= v <= hi_r):
            sys.exit(f"ERROR: sample {lineno_hint} value {v} is outside ap_fixed<{w},{i}>, "
                     f"whose range is [{lo_r}, {hi_r}].\n"
                     f"       Scale your data, or widen FFT_IN_W / FFT_IN_I in src/fft_top.hpp.")
        # Python's round() is half-to-even.  Which tie rule is used here does not affect the
        # comparison -- the DUT and the model both receive this same stored integer -- it only
        # decides which representable value your decimal lands on.
        return round(v * 2.0 ** frac)

    out = Path(args.out)
    if not out.is_absolute():
        out = HERE / out
    lines = [f"# Generated by encode_input.py from {src.name}",
             f"# raw STORED integers of ap_fixed<{w},{i}>: stored = round(real * 2**{frac})",
             "# format:  <n_vectors> <n_samples>   then one 're im' pair per line, vector-major",
             f"{n_vec} {length}"]
    for idx, (re_v, im_v) in enumerate(pairs):
        lines.append(f"{store(re_v, idx)} {store(im_v, idx)}")
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.relative_to(HERE)}: {n_vec} vector(s) x {length} samples, "
          f"ap_fixed<{w},{i}>")
    print(f"next:  WF_INPUT={out.name} vitis-run --mode hls --tcl run.tcl")
    print(f"       python verify.py --input {out.name}")


if __name__ == "__main__":
    main()
