// state_accum_bfm_tb.cpp -- GENERATED by waveflow (build/composite_gen.py::render_tb_main)
// from the state_accum testbench graph.  DO NOT EDIT: regenerate instead.
//
// The whole TB main: construct the generated harness, run a fixed number of cycles (the
// participants load their input bundles in pre_sim and dump their outputs in post_sim), then
// close.  No golden here -- correctness is checked in Python from the dumped output bundles.
#include "state_accum_tb_harness.h"

int main() {
    state_accum_tb::Harness h("state_accum_bfm.wdb");
    h.run(400);
    h.close();
    return 0;
}
